import { StyleSheet, Platform } from "react-native";
import { theme } from "@/shared/theme/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  content: { padding: 16 },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  title: { fontSize: 22, fontWeight: "700", marginBottom: 8, color: theme.colors.text },
  help: { fontSize: 14, color: theme.colors.textSecondary, marginBottom: 12 },
  row: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  progressHeader: { marginBottom: 12 },
  progressText: { marginBottom: 6, color: theme.colors.text, fontWeight: "600" },
  progressSubtext: { marginTop: 6, color: theme.colors.textSecondary },
  progressTrack: { height: 8, backgroundColor: theme.colors.surface, borderRadius: 999 },
  progressBar: { height: 8, backgroundColor: theme.colors.primary, borderRadius: 999 },
  error: { color: "#EF4444", marginTop: -6, marginBottom: 8 },
  suggestionsContainer: {
    gap: 4,
    marginTop: -8,
    marginBottom: 8,
  },
  suggestionButton: {
    padding: 12,
    backgroundColor: "#F9FAFB",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 4,
  },
  suggestionText: {
    fontSize: 14,
    color: "#333333",
  },
  fieldContainer: { marginBottom: 16 },
  fieldLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 8,
  },
  dualInputContainer: { flexDirection: "row", gap: 12 },
  input: { flex: 1 },
  unitPicker: {
    backgroundColor: theme.colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Platform.OS === "ios" ? "#C7C7CC" : "#DDD",
    minWidth: 80,
    ...(Platform.OS === "ios" && {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
    }),
  },
  picker: {
    height: 50,
    backgroundColor: "transparent",
  },
  pickerContainer: {
    backgroundColor: theme.colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Platform.OS === "ios" ? "#C7C7CC" : "#DDD",
    ...(Platform.OS === "ios" && {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
    }),
  },
  fullPicker: {
    height: 50,
    backgroundColor: "transparent",
  },
  lifeDomainContainer: {
    marginBottom: 24,
    padding: 16,
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E9ECEF",
  },
  lifeDomainLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 12,
  },
  sliderContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  sliderValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#4CAF50",
    minWidth: 40,
    textAlign: "center",
  },
  sliderWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sliderMin: {
    fontSize: 12,
    color: "#666666",
    minWidth: 20,
  },
  sliderMax: {
    fontSize: 12,
    color: "#666666",
    minWidth: 30,
  },
  sliderTrack: {
    flex: 1,
    height: 6,
    backgroundColor: "#E9ECEF",
    borderRadius: 3,
    position: "relative",
  },
  sliderFill: {
    height: "100%",
    backgroundColor: "#4CAF50",
    borderRadius: 3,
  },
  sliderThumb: {
    position: "absolute",
    top: -8,
    width: 22,
    height: 22,
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "#4CAF50",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  slider: {
    flex: 1,
    height: 40,
    marginHorizontal: 16,
  },
  sliderLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  sliderLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 8,
  },
  sliderSubLabel: {
    fontSize: 12,
    color: "#666666",
    marginTop: 8,
    marginBottom: 4,
  },
  sliderMinMax: {
    fontSize: 12,
    color: "#666666",
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 16,
  },
  photoContainer: {
    width: "30%",
    aspectRatio: 1,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: theme.colors.surface,
    position: "relative",
  },
  uploadingPhotoContainer: {
    width: "30%",
    aspectRatio: 1,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  photo: {
    width: "100%",
    height: "100%",
  },
  removePhotoButton: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    borderRadius: 15,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  removePhotoText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "bold",
  },
  addPhotoButton: {
    width: "30%",
    aspectRatio: 1,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    borderWidth: 2,
    borderColor: "#E5E5EA",
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
  },
  addPhotoText: {
    fontSize: 32,
    color: "#666666",
    fontWeight: "300",
  },
  addPhotoLabel: {
    fontSize: 12,
    color: "#666666",
    marginTop: 4,
  },
  uploadingText: {
    fontSize: 12,
    color: "#666666",
    marginTop: 8,
    textAlign: "center",
  },
  typologySection: {
    marginBottom: 20,
    padding: 16,
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E9ECEF",
  },
  typologyTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 12,
  },
  alertContainer: {
    backgroundColor: "#E3F2FD",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BBDEFB",
    marginBottom: 20,
  },
  alertTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1976D2",
    marginBottom: 8,
  },
  alertText: {
    fontSize: 14,
    color: "#1976D2",
    marginBottom: 16,
    lineHeight: 20,
  },
  questionsScroll: {
    maxHeight: 400,
    marginBottom: 20,
  },
  domainSection: {
    marginBottom: 24,
    padding: 16,
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E9ECEF",
  },
  domainTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 16,
  },
  questionContainer: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E9ECEF",
  },
  questionLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333333",
    marginBottom: 8,
    lineHeight: 22,
  },
  toggleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
  },
  toggleLabel: {
    fontSize: 14,
    color: "#666666",
    fontWeight: "500",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  modalContent: {
    padding: 24,
    paddingTop: 40,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#333333",
    marginBottom: 16,
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 12,
    textAlign: "center",
  },
  modalText: {
    fontSize: 16,
    color: "#666666",
    lineHeight: 24,
    marginBottom: 16,
  },
  tipContainer: {
    flexDirection: "row",
    marginBottom: 12,
    alignItems: "flex-start",
  },
  tipNumber: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
    marginRight: 8,
    minWidth: 20,
  },
  tipText: {
    fontSize: 16,
    color: "#666666",
    lineHeight: 24,
    flex: 1,
  },
  modalButtons: {
    marginTop: 24,
    alignItems: "center",
  },
  domainButton: {
    marginBottom: 12,
  },
  sectionHeader: {
    marginVertical: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 8,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: "#666666",
    lineHeight: 20,
    fontStyle: "italic",
  },
});

