import { createInitialParallelStreamingTtsState } from '@features/aria/interviewParallelTtsBatch';
import type { PreClaudeTurnGateDeps } from '@features/aria/preClaudeTurnGateTypes';
import { mockRef } from './postClaudeGateTestHelpers';

export function createMockPreClaudeDeps(
  overrides: Partial<PreClaudeTurnGateDeps> = {},
): PreClaudeTurnGateDeps {
  const noop = jest.fn();
  const asyncNoop = jest.fn().mockResolvedValue(undefined);

  return {
    messages: [],
    userId: 'user-test',
    isAdmin: false,
    isInterviewAppRoute: true,
    status: 'active',
    closingQuestionPending: false,
    closingQuestionScenario: null,
    usedPersonalExamples: false,
    setVoiceState: noop,
    setIsWaiting: noop,
    setMessages: noop,
    setCurrentTranscript: noop,
    setExchangeCount: noop,
    setHighestScenarioReached: jest.fn((updater) => {
      if (typeof updater === 'function') updater(1);
    }),
    setClosingQuestionPending: noop,
    setClosingQuestionScenario: noop,
    setInterviewStatus: noop,
    setPendingCompletion: noop,
    setResults: noop,
    setStatus: noop,
    setTouchedConstructs: noop,
    setUsedPersonalExamples: noop,
    setReferenceCardPrompt: noop,
    commitInterviewMessages: noop,
    speakTextSafe: asyncNoop,
    deliverRecordingRetryLine: asyncNoop,
    invalidateProfileQuery: noop,
    applyInterviewProgressFromAssistantText: noop,
    scoreScenario: noop,
    notifyScenarioStarted: asyncNoop,
    ensureCompletedScenarioScored: noop,
    markClosingQuestionAsked: noop,
    markClosingQuestionAnswered: noop,
    runEmotionModalAfterScenarioTransition: asyncNoop,
    awaitEmotionModalForIndex: asyncNoop,
    kickPostClosingInterviewCompletionIfReady: jest.fn().mockResolvedValue(false),
    kickCompletionScoring: jest.fn().mockReturnValue(false),
    showChatError: noop,
    createInterviewAttemptOnFirstSubstantiveResponse: jest.fn().mockResolvedValue('attempt-1'),
    collectDeviceContext: jest.fn().mockResolvedValue({ platform: 'web' }),
    resetSessionLogRuntime: noop,
    assignAttemptIdForSessionLogs: noop,
    markAiProcessingTurnStarted: noop,
    metaClassificationForPendingAssistantRef: mockRef(null),
    whisperRatioReaskAttemptsForCurrentQuestionRef: mockRef(0),
    resumeRepeatChoicePendingRef: mockRef(false),
    resumeLastAssistantTextRef: mockRef(null),
    lastQuestionTextRef: mockRef(''),
    parallelStreamingTtsRef: mockRef(createInitialParallelStreamingTtsState()),
    ttsLineInFlightRef: mockRef(false),
    ttsUtteranceInFlightRef: mockRef(null),
    interviewSessionIdRef: mockRef('session-test'),
    interviewSessionAttemptIdRef: mockRef('attempt-test'),
    interviewAttemptCreationInFlightRef: mockRef(false),
    interviewNameRef: mockRef('Alex'),
    interviewNameReaskPendingRef: mockRef(false),
    interviewNameReaskUsedRef: mockRef(false),
    interviewStatusRef: mockRef('active'),
    currentInterviewMomentRef: mockRef(1),
    currentScenarioRef: mockRef(1),
    currentMessagesRef: mockRef([]),
    transcriptAtReleaseRef: mockRef(''),
    frustrationSkipOfferPendingRef: mockRef(false),
    frustrationSkipAwaitingConfirmationRef: mockRef(false),
    frustrationSkipHadPriorAnswerRef: mockRef(null),
    scenarioSkipOfferSourceRef: mockRef(null),
    metaCommentAckAwaitingSubstantiveBaselineSeqRef: mockRef(null),
    substantiveInterviewQuestionDeliveredSeqRef: mockRef(0),
    metaCommentFrustrationCountByMomentRef: mockRef({}),
    inabilityCountByMomentRef: mockRef({}),
    skipRequestClassificationSeenByMomentRef: mockRef({}),
    scenarioCSophiePerspectiveProbeFiredRef: mockRef(false),
    probeLogRef: mockRef([]),
    elongatingProbeFiredRef: mockRef(false),
    personalHandoffInjectedRef: mockRef(false),
    interviewMomentsCompleteRef: mockRef({}),
    scoredScenariosRef: mockRef(new Set<number>()),
    scenarioScoresRef: mockRef({}),
    scenarioAContemptProbeAskedRef: mockRef(false),
    scenarioARepairQuestionAskedRef: mockRef(false),
    s2RepairProbeDeliveredRef: mockRef(false),
    s3RepairProbeDeliveredRef: mockRef(false),
    scenarioAContemptProbeTtsDeliveredSessionRef: mockRef(false),
    moment4ThresholdProbeAskedRef: mockRef(false),
    deliveredReflectionRegistryRef: mockRef([]),
    moment4ClientSpecificityProbeInjectedRef: mockRef(false),
    moment4ExpectingPostSpecificityUserTurnRef: mockRef(false),
    moment4PostGrudgeSpecificityResolvedRef: mockRef(false),
    moment4SpecificityScoringRef: mockRef(null),
    deferredMoment4NarrativeRef: mockRef(null),
    moment5AccountabilityProbeFiredRef: mockRef(false),
    moment5PostPromptUserTurnCountRef: mockRef(0),
    moment5PrimaryAnchorDeliveredSessionRef: mockRef(false),
    moment5QuestionDeliveredRef: mockRef(false),
    moment5QuestionDeliveryInFlightRef: mockRef(false),
    moment5ResolutionFollowUpIssuedRef: mockRef(false),
    moment5ResolutionDeliveredRef: mockRef(false),
    moment5ClientScoringMetaRef: mockRef(null),
    moment5ConflictValidityClarificationIssuedRef: mockRef(false),
    moment5SpecificityRedirectIssuedRef: mockRef(false),
    waitingForClosingAdditionRef: mockRef(null),
    lastAnsweredClosingScenarioRef: mockRef(null),
    lastClosingQuestionScenarioRef: mockRef(null),
    closingQuestionAskedRef: mockRef({}),
    closingQuestionAnsweredRef: mockRef({}),
    skipContinuationSystemSuffixRef: mockRef(''),
    resumeActiveScenarioRef: mockRef(null),
    isInterviewCompleteRef: mockRef(false),
    pendingCompletionTranscriptRef: mockRef(null),
    pendingEmotionModalTransitionRef: mockRef(null),
    resetScenarioCClientGatesOnly: noop,
    emotionItemResponsesRef: mockRef([]),
    recordInterviewAssistantDeliveryForMetaExemptionRef: mockRef(noop),
    finalizePendingMetaAckBaselineAfterAssistantTextRef: mockRef(noop),
    pendingScenarioAContemptProbeStreamMuteRef: mockRef(false),
    pendingS3ToM4HandoffStreamMuteRef: mockRef(false),
    resumeClosingRepeatSpeakInFlightRef: mockRef(false),
    resumeRepeatPrefetchMpegRef: mockRef(null),
    routeChangedDuringRecordingRef: mockRef(false),
    scenarioCRepairOnlyEvidenceRef: mockRef(null),
    scenarioFrustrationSkipNullMarkersRef: mockRef({}),
    scenarioSkipConfirmedCountRef: mockRef(0),
    scenarioSkipPenaltySumRef: mockRef(0),
    lastUserTurnAudioDurationMsRef: mockRef(null),
    lastVoiceTurnConfidenceRef: mockRef(null),
    lastVoiceTurnLanguageRef: mockRef(null),
    responseTimingsRef: mockRef([]),
    timingRef: mockRef({}),
    resumeLoadingFlowActiveRef: mockRef(false),
    resumeOfferWelcomeTtsRef: mockRef(false),
    interviewUserTurnEpochRef: mockRef(0),
    ...overrides,
  };
}
