import { StyleSheet } from 'react-native';

export const cohortListStyles = StyleSheet.create({
  exportRow: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  exportCsvButton: {
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.35)',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: 'rgba(30,111,217,0.15)',
  },
  exportCsvButtonDisabled: {
    opacity: 0.45,
  },
  exportCsvButtonText: {
    color: '#C8E4FF',
    fontSize: 13,
    fontWeight: '600',
  },
  cohortToolbar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    columnGap: 10,
    rowGap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(82,142,220,0.1)',
  },
  userSearchBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(82,142,220,0.08)',
  },
  userSearchInput: {
    flex: 1,
    minWidth: 180,
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.3)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: '#E8F0F8',
    fontSize: 13,
    backgroundColor: 'rgba(5,6,13,0.35)',
  },
  userSearchClearBtn: {
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  userSearchClearText: {
    color: '#7A9ABE',
    fontSize: 12,
    fontWeight: '600',
  },
  cohortStatsRowInline: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  cohortStatPill: {
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.2)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    minWidth: 72,
  },
  cohortStatValSmall: {
    color: '#C8E4FF',
    fontSize: 16,
    fontWeight: '600',
  },
  cohortStatLblSmall: {
    color: '#7A9ABE',
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginTop: 1,
  },
  filterCluster: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 5,
  },
  filterClusterGrow: {
    flexBasis: 220,
    flexGrow: 1,
  },
  filterClusterLabel: {
    color: '#5C7A9E',
    fontSize: 9,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginRight: 2,
  },
  filterChipCompact: {
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.22)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  filterChipActive: {
    backgroundColor: 'rgba(30,111,217,0.2)',
    borderColor: 'rgba(82,142,220,0.45)',
  },
  filterChipTextCompact: {
    color: '#7A9ABE',
    fontSize: 11,
    fontWeight: '500',
  },
  filterChipTextActive: {
    color: '#C8E4FF',
  },
  filterCustomRangeRow: {
    width: '100%' as const,
    flexBasis: '100%' as const,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    columnGap: 6,
    rowGap: 4,
    marginTop: 1,
  },
  customDateInput: {
    minWidth: 108,
    maxWidth: 120,
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.3)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    color: '#E8F0F8',
    fontSize: 11,
    backgroundColor: 'rgba(5,6,13,0.4)',
  },
  filterCustomHint: {
    color: '#5C7A9E',
    fontSize: 9,
    flexBasis: '100%' as const,
  },
  cardsContainer: {
    padding: 20,
    gap: 12,
  },
  emptyText: {
    color: '#7A9ABE',
    fontSize: 13,
    textAlign: 'center',
  },
  listErrorBlock: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(248,113,113,0.35)',
    backgroundColor: 'rgba(248,113,113,0.08)',
    gap: 10,
  },
  listErrorTitle: {
    color: '#fecaca',
    fontSize: 15,
    fontWeight: '600',
  },
  listErrorDetail: {
    color: 'rgba(254,226,226,0.92)',
    fontSize: 12,
    lineHeight: 18,
  },
  listErrorHint: {
    color: '#7A9ABE',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
});
