import { StyleSheet } from 'react-native';

export const summaryTabStyles = StyleSheet.create({
  overrideChip: {
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.35)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: 'rgba(30,111,217,0.12)',
  },
  overrideChipText: {
    color: '#C8E4FF',
    fontSize: 12,
    fontWeight: '600',
  },
  summaryModifierHint: {
    fontSize: 11,
    color: 'rgba(180, 198, 220, 0.75)',
    marginTop: 2,
    marginLeft: 0,
  },
  summaryModifierRed: {
    color: '#E87A7A',
    fontWeight: '600',
  },
  innerTabContent: {
    flex: 1,
    padding: 14,
  },
  sectionTitle: {
    color: '#C8E4FF',
    fontSize: 14,
    marginTop: 4,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(82,142,220,0.08)',
  },
  metaLabel: {
    color: '#7A9ABE',
    fontSize: 12,
  },
  metaValue: {
    color: '#E8F0F8',
    fontSize: 12,
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  scoreLabel: {
    color: '#7A9ABE',
    fontSize: 12,
  },
  scoreValue: {
    color: '#C8E4FF',
    fontSize: 12,
  },
  block: {
    marginTop: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.12)',
    borderRadius: 8,
    backgroundColor: 'rgba(13,17,32,0.5)',
  },
  blockTitle: {
    color: '#C8E4FF',
    fontSize: 13,
    marginBottom: 6,
  },
  blockText: {
    color: '#7A9ABE',
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 4,
  },
  styleTranslationNote: {
    marginBottom: 8,
    fontStyle: 'italic',
    opacity: 0.95,
  },
  styleBarRow: {
    marginTop: 8,
  },
  styleBarValueCol: {
    marginTop: 4,
    alignItems: 'flex-start',
  },
  styleExperienceLabel: {
    fontSize: 11,
    color: '#9BB8D9',
    marginTop: 2,
    flexShrink: 1,
  },
  styleBarTrack: {
    marginTop: 4,
    width: '100%',
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(82,142,220,0.15)',
    overflow: 'hidden',
  },
  styleBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#5BA8E8',
  },
  reprocessButton: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.5)',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(30,111,217,0.14)',
    alignItems: 'center',
  },
  reprocessButtonPressed: {
    backgroundColor: 'rgba(30,111,217,0.24)',
  },
  reprocessButtonText: {
    color: '#C8E4FF',
    fontSize: 12,
    fontWeight: '600',
  },
  commFloorReviewBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    overflow: 'hidden',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  commFloorDismissButton: {
    marginTop: 10,
    alignSelf: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(212, 168, 75, 0.55)',
    backgroundColor: 'rgba(212, 168, 75, 0.12)',
  },
  commFloorDismissButtonText: {
    color: '#F2E6BF',
    fontSize: 12,
    fontWeight: '600',
  },
  commFloorModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    padding: 24,
  },
  commFloorModalCard: {
    borderRadius: 12,
    padding: 16,
    backgroundColor: 'rgba(18,22,38,0.98)',
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.25)',
    maxWidth: 520,
    alignSelf: 'center',
    width: '100%',
  },
  commFloorModalTitle: {
    color: '#C8E4FF',
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 8,
  },
  commFloorModalInput: {
    marginTop: 10,
    minHeight: 88,
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.25)',
    borderRadius: 8,
    padding: 10,
    color: '#E8F0F8',
    fontSize: 13,
    textAlignVertical: 'top',
  },
  commFloorModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 14,
  },
  commFloorModalCancel: {
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  commFloorModalCancelText: {
    color: '#7A9ABE',
    fontSize: 13,
    fontWeight: '600',
  },
  commFloorModalConfirm: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(212, 168, 75, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(212, 168, 75, 0.45)',
  },
  commFloorModalConfirmText: {
    color: '#F2E6BF',
    fontSize: 13,
    fontWeight: '700',
  },
});
