/** Symbols wired directly by AriaScreen for hook param / sync-ctx assembly. */

export { isAmoraeaAdminConsoleEmail } from '@/constants/adminConsole';
export { supabase } from '@data/supabase/client';
export { kickCompletionScoring, markCompletionScoringInFlight, resetCompletionScoringSession } from '@features/aria/completionScoringKick';
export { composeAriaInterviewServicesGateSyncContextLayer } from '@features/aria/composeAriaInterviewSyncContextLayers';
export { setAudioRouteKind } from '@features/aria/config/audioRouteRuntime';
export { isApprovedElongatingProbeOnly } from '@features/aria/elongatingProbe';
export { listUnansweredEmotionModalIndices } from '@features/aria/emotionRecognitionInterview';
export { hasInterviewClosingSpeakInFlightForSession, resetInterviewClosingTtsSession } from '@features/aria/interviewClosingTtsSession';
export { stripControlTokens } from '@features/aria/interviewControlTokens';
export { getInterviewUserFirstNameForPrompt } from '@features/aria/interviewerFrameworkPrompt';
export { clearPreparingResultsSession, clearResumeWelcomePlaybackLock, hasPreparingResultsSession, markPreparingResultsSession, saveInterviewProgress } from '@features/aria/interviewLocalPersistence';
export { applyInterviewProgressFromAssistantText, createInitialMomentCompletion } from '@features/aria/interviewProgressSync';
export { detectActiveScenarioFromMessage } from '@features/aria/interviewScenarioOpeningStreamGate';
export { setInterviewJustCompletedInSession, setInterviewLastCommittedAttemptId, takeInterviewJustCompletedInSession, takeInterviewLastCommittedAttemptId } from '@features/aria/interviewSessionGlobals';
export { countsAsSubstantiveInterviewQuestionDelivery } from '@features/aria/metaCommentClassification';
export { looksLikeMoment4GrudgePrompt, looksLikeMoment4ThresholdQuestion } from '@features/aria/moment4ProbeLogic';
export { looksLikeMoment4SpecificityFollowUpPrompt } from '@features/aria/moment4SpecificityFollowUp';
export { isMoment5AssistantAnchor, isScenarioCQ1Prompt, looksLikeMoment5AccountabilityProbeAssistantPrompt } from '@features/aria/probeAndScoringUtils';
export { detectScenarioFromResponse, getScenarioNumberForNewMessage } from '@features/aria/scenarioNumberDetection';
export { prepareInterviewTtsPlayback } from '@features/aria/utils/audioModeHelpers';
export { stopElevenLabsPlayback, stopElevenLabsSpeech } from '@features/aria/utils/elevenLabsTtsPlaybackStop';
export { resetInterviewVadSession } from '@features/aria/utils/interviewVadSession';
/** Legacy browser-gesture hooks — retained as no-ops for SyncExtra wiring. */
export const bumpAriaScreenMountGeneration = (): void => {};
export const markAiProcessingTurnStarted = (): void => {};
export const resetWebInterviewGestureContext = (): void => {};
export { resolveInterviewCompletedForUser } from '@features/psychometrics/interviewCompletionStatus';
export { isValidationTrackInterviewHandoffActive } from '@features/relationshipValidation/validationPostInterviewRouting';
export { showConfirmDialog, showSimpleAlert } from '@utilities/alerts/confirmDialog';
export { persistInterviewAttemptSessionLifecycle } from '@utilities/interviewAttemptLifecycle';
export { remoteLog } from '@utilities/remoteLog';
export { runCommunicationStylePipelineAfterSave } from '@utilities/runCommunicationStylePipeline';
export { assignAttemptIdForSessionLogs, getSessionLogRuntime, resetSessionLogRuntime, setSessionLogPlatform, setTtsPlaybackActive, touchActivity } from '@utilities/sessionLogging';
export { resetAudioInterviewTurnCounters, setAudioSessionDeviceSnapshot, setLastInterviewDeviceEnvironment, setLastTtsCompletionCallbackMs, setSessionAudioRoutes } from '@utilities/sessionLogging/audioSessionLogEnvelope';
export { collectDeviceContext } from '@utilities/sessionLogging/collectDeviceContext';
export { markSessionResumedForNextRecordingStart } from '@utilities/sessionLogging/sessionResumeRecordingTelemetry';
export { resetTtsDurationCalibration } from '@utilities/sessionLogging/ttsDurationCalibration';
export { hasCachedWebMicTrackSettings, resetWebAudioRouteSessionFingerprint, syncWebAudioRouteSessionEnvelopeFromCache } from '@utilities/sessionLogging/webMediaDeviceAudioRoute';
export { writeSessionLog } from '@utilities/sessionLogging/writeSessionLog';
export { clearInterviewFromStorage, loadInterviewFromStorage, saveInterviewToStorage } from '@utilities/storage/InterviewStorage';
export { syncLiveInterviewTranscriptToAttempt } from '@utilities/syncLiveInterviewTranscript';
export { waitForInterviewAttemptScoringReady } from '@utilities/waitForInterviewAttemptScoringReady';
export { classifyError } from '@utilities/withRetry';
