export const SCENARIO_A_CONTEMPT_RECOGNITION_CALIBRATION = `
Scenario A — CONTEMPT RECOGNITION (Emma/Ryan):
- **contempt_recognition:** Whether they identify contemptuous or harsh dynamics in the fiction (Emma's line, the exchange). Accurate reads of coldness, dismissal, shutting down, sarcasm, bitterness, hostility, or relational sting support strong recognition scores. Generic hurt with no relational read -> partial recognition is fine; do not require the word "contempt."
- Contempt recognition requires identifying the **emotional register** of Emma's contemptuous statement — the sharpness, dismissiveness, bitterness, sarcasm, or hostility in how it was delivered — not just that it reflects accumulated frustration or a recurring pattern.
- For Scenario A specifically, "you've made that very clear" contains: sarcastic acknowledgment that signals Emma has given up trying to change the behavior; dismissive closure that shuts down Ryan's attempt to engage; and an implicit contemptuous framing of Ryan as someone whose behavior is settled and predictably negative.
- **Register-neutral analytical reads:** A user who accurately names dismissive closure, shut-down, bitter resignation, sarcastic foreclosing of repair, or that Emma's line ends Ryan's bid before he speaks (even in cool/clinical/analytical vocabulary) has identified contempt **register** — score **7–8** when accurate. Do **not** cap at 4–5 solely because they also named recurrence or frustration; the cap applies only when the answer is **pattern-only** with **no** tone, sting, dismissal, shut-down, or closure language.
- Pattern recognition alone is not contempt recognition. A user who says only "she's frustrated because this has happened before" with no dismissive/shut-down/sarcastic register has identified recurrence but not contempt. Score contempt_recognition around 3-4 for **that pattern-only** evidence.
- **Partial recognition (5–6):** When the user links Emma's line to **accumulated relational hurt** or a **recurring dynamic** (e.g. "they've had this before," "it hurt her how clearly he's established his priority," "she's tired of him making that point") **without** naming dismissive shut-down, sarcasm, or bitter resignation, score **5–6** — competent partial recognition. Do **not** score 3–4 when they connect the line to ongoing relational impact; reserve 3–4 for plot restatement or generic frustration with no read of the exchange's sting.
- If the user identifies only the pattern without any emotional register or relational-impact read, cap contempt_recognition at 4-5 regardless of how accurately they describe the recurrence.
- If the user identifies both the pattern and the emotional register (including analytical descriptions of shut-down, dismissal, or bitter resignation), score contempt_recognition in the 7-8 range when otherwise accurate.
- A user who says "that line has a sharp, sarcastic edge — she's not just frustrated, she's signaling that she's stopped expecting things to change" has identified the contemptuous register. Score around 7-8.
- A user who says "you've made that very clear is contemptuous — it dismisses anything Ryan might say next before he even says it; it's a shut-down, not a complaint" has identified the mechanism of contempt. Score around 8-9.
- **contempt_expression:** Use only the **CONTEMPT_EXPRESSION** rubric in this prompt. Ordinary disapproval of **bad behavior** (rude, wrong, inconsiderate, dishonoring a *specific* act) is not the same as a **low (1-4)** expression score; those bands are for character attack, mockery, dehumanization, sweeping "who they are" verdicts. Score **contempt_expression** independently of **contempt_recognition**.
`.trim();
