import type { MutableRefObject } from 'react';

import { runApplyRouteProbeAfterResume } from '@features/aria/applyRouteProbeAfterResumeTypes';
import { markNativePlaybackBridgeBeforeNextTts } from '@features/aria/utils/audioModeHelpers';
import type { InterviewSessionLifecycleDeps, HandleResumeDeps } from '@features/aria/sessionLifecycleTypes';
import type { ScoreInterviewDeps } from '@features/aria/scoreInterviewTypes';
import type {
  AriaInterviewDepsRefs,
  AriaInterviewDepsSyncContext,
} from '@features/aria/syncAriaInterviewDepsTypes';

export function syncSessionLifecycleDeps(
  ref: MutableRefObject<InterviewSessionLifecycleDeps>,
  ctx: AriaInterviewDepsSyncContext,
): void {
  ref.current = {
    userId: ctx.userId,
        isAdmin: ctx.isAdmin,
        isInterviewAppRoute: ctx.isInterviewAppRoute,
        status: ctx.status,
        interviewStatus: ctx.interviewStatus,
        interviewAttemptBootstrap: ctx.interviewAttemptBootstrap,
        onboardingAutoStartRef: ctx.onboardingAutoStartRef,
        speakTextSafe: ctx.speakTextSafe,
        awaitScreenReadySignal: ctx.awaitScreenReadySignal,
        logSessionResumeState: ctx.logSessionResumeState,
        awaitEmotionModalForIndex: ctx.awaitEmotionModalForIndex,
        notifyScenarioStarted: ctx.notifyScenarioStarted,
        resetInterviewProgressRefs: ctx.resetInterviewProgressRefs,
        interruptAllInterviewTtsOutput: ctx.interruptAllInterviewTtsOutput,
        audioRecorder: ctx.audioRecorder,
        profile: ctx.profile,
        hasResumedRef: ctx.hasResumedRef,
        resumeLoadingFlowActiveRef: ctx.resumeLoadingFlowActiveRef,
        resumeHandleInFlightRef: ctx.resumeHandleInFlightRef,
        setResumeLoadingVisible: ctx.setResumeLoadingVisible,
        setResumeHydrationPending: ctx.setResumeHydrationPending,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        interviewSessionIdRef: ctx.interviewSessionIdRef,
        interviewMomentsCompleteRef: ctx.interviewMomentsCompleteRef,
        currentInterviewMomentRef: ctx.currentInterviewMomentRef,
        personalHandoffInjectedRef: ctx.personalHandoffInjectedRef,
        interviewNameRef: ctx.interviewNameRef,
        moment4ThresholdProbeAskedRef: ctx.moment4ThresholdProbeAskedRef,
        deliveredReflectionRegistryRef: ctx.deliveredReflectionRegistryRef,
        moment4PostGrudgeSpecificityResolvedRef: ctx.moment4PostGrudgeSpecificityResolvedRef,
        moment4ClientSpecificityProbeInjectedRef: ctx.moment4ClientSpecificityProbeInjectedRef,
        moment5AccountabilityProbeFiredRef: ctx.moment5AccountabilityProbeFiredRef,
        moment5SpecificityRedirectIssuedRef: ctx.moment5SpecificityRedirectIssuedRef,
        moment5ResolutionFollowUpIssuedRef: ctx.moment5ResolutionFollowUpIssuedRef,
        moment5ResolutionDeliveredRef: ctx.moment5ResolutionDeliveredRef,
        moment5ConflictValidityClarificationIssuedRef: ctx.moment5ConflictValidityClarificationIssuedRef,
        moment5QuestionDeliveredRef: ctx.moment5QuestionDeliveredRef,
        moment5PrimaryAnchorDeliveredSessionRef: ctx.moment5PrimaryAnchorDeliveredSessionRef,
        moment5PostPromptUserTurnCountRef: ctx.moment5PostPromptUserTurnCountRef,
        scenarioAContemptProbeAskedRef: ctx.scenarioAContemptProbeAskedRef,
        scenarioAContemptProbeTtsDeliveredSessionRef: ctx.scenarioAContemptProbeTtsDeliveredSessionRef,
        scenarioAContemptProbePlaybackConfirmedRef: ctx.scenarioAContemptProbePlaybackConfirmedRef,
        showScenarioCardCanonicalPlaybackConfirmedKindsRef:
          ctx.showScenarioCardCanonicalPlaybackConfirmedKindsRef,
        scenarioARepairQuestionAskedRef: ctx.scenarioARepairQuestionAskedRef,
        s2RepairProbeDeliveredRef: ctx.s2RepairProbeDeliveredRef,
        s3RepairProbeDeliveredRef: ctx.s3RepairProbeDeliveredRef,
        probeLogRef: ctx.probeLogRef,
        scoredScenariosRef: ctx.scoredScenariosRef,
        setHighestScenarioReached: ctx.setHighestScenarioReached,
        currentScenarioRef: ctx.currentScenarioRef,
        resumeActiveScenarioRef: ctx.resumeActiveScenarioRef,
        emotionItemResponsesRef: ctx.emotionItemResponsesRef,
        setEmotionItemResponses: ctx.setEmotionItemResponses,
        setEmotionItemsComplete: ctx.setEmotionItemsComplete,
        resumeEmotionCatchUpIndicesRef: ctx.resumeEmotionCatchUpIndicesRef,
        resumeEmotionAfterModalTextRef: ctx.resumeEmotionAfterModalTextRef,
        resumeOfferWelcomeTtsRef: ctx.resumeOfferWelcomeTtsRef,
        resumeInPersonalPartRef: ctx.resumeInPersonalPartRef,
        resumeWelcomeMessageRef: ctx.resumeWelcomeMessageRef,
        resumeWelcomeHydrationAttemptRef: ctx.resumeWelcomeHydrationAttemptRef,
        resumeLastAssistantTextRef: ctx.resumeLastAssistantTextRef,
        lastQuestionTextRef: ctx.lastQuestionTextRef,
        scenarioSkipConfirmedCountRef: ctx.scenarioSkipConfirmedCountRef,
        scenarioSkipPenaltySumRef: ctx.scenarioSkipPenaltySumRef,
        setMessages: ctx.setMessages,
        pendingCompletionTranscriptRef: ctx.pendingCompletionTranscriptRef,
        setPendingCompletion: ctx.setPendingCompletion,
        isInterviewCompleteRef: ctx.isInterviewCompleteRef,
        interviewStatusRef: ctx.interviewStatusRef,
        setInterviewStatus: ctx.setInterviewStatus,
        setScenarioScores: ctx.setScenarioScores,
        setStageResults: ctx.setStageResults,
        setTouchedConstructs: ctx.setTouchedConstructs,
        pendingScenarioIntroAfterResumeWelcomeRef: ctx.pendingScenarioIntroAfterResumeWelcomeRef,
        resumeRepeatChoicePendingRef: ctx.resumeRepeatChoicePendingRef,
        setStatus: ctx.setStatus,
        committedScenarioRef: ctx.committedScenarioRef,
        setReferenceCardScenario: ctx.setReferenceCardScenario,
        setReferenceCardPrompt: ctx.setReferenceCardPrompt,
        setInterviewUiPhase: ctx.setInterviewUiPhase,
        currentMessagesRef: ctx.currentMessagesRef,
        interruptAllInterviewTtsOutput: ctx.interruptAllInterviewTtsOutput,
        moment5QuestionDeliveryInFlightRef: ctx.moment5QuestionDeliveryInFlightRef,
        interviewUserTurnEpochRef: ctx.interviewUserTurnEpochRef,
        processUserSpeech: ctx.processUserSpeech as HandleResumeDeps['processUserSpeech'],
        prepareInterviewAudioForResumePlayback: async () => {
          const { setRecordingSessionActive } = await import('@utilities/sessionLogging');
          setRecordingSessionActive(false);
          markNativePlaybackBridgeBeforeNextTts('resume_prepare_audio');
          await ctx.audioRecorder.reinitializeMicrophoneSession();
          await runApplyRouteProbeAfterResume(
            {
              userIdRef: (ctx.userIdRef ?? { current: ctx.userId }) as MutableRefObject<string | undefined>,
              lastAudioRouteFingerprintRef: ctx.lastAudioRouteFingerprintRef,
              lastHeadphoneProbeRef: ctx.lastHeadphoneProbeRef,
              setAudioRouteKind: ctx.setAudioRouteKind,
            },
            'app_resume',
          );
        },
        startInterviewInFlightRef: ctx.startInterviewInFlightRef,
        setInterviewStartInFlight: ctx.setInterviewStartInFlight,
        setMicError: ctx.setMicError,
        setVoiceState: ctx.setVoiceState,
        setMicPermission: ctx.setMicPermission,
        lastHeadphoneProbeRef: ctx.lastHeadphoneProbeRef,
        setAudioRouteKind: ctx.setAudioRouteKind,
        lastAudioRouteFingerprintRef: ctx.lastAudioRouteFingerprintRef,
        recordingJustFinishedBeforeNextTtsRef: ctx.recordingJustFinishedBeforeNextTtsRef,
        postRecordingParallelStreamSettleRef: ctx.postRecordingParallelStreamSettleRef,
        lastVoiceTurnLanguageRef: ctx.lastVoiceTurnLanguageRef,
        lastVoiceTurnConfidenceRef: ctx.lastVoiceTurnConfidenceRef,
        setSessionLogPlatform: ctx.setSessionLogPlatform,
        setAudioSessionDeviceSnapshot: ctx.setAudioSessionDeviceSnapshot,
        setLastInterviewDeviceEnvironment: ctx.setLastInterviewDeviceEnvironment,
        setSessionAudioRoutes: ctx.setSessionAudioRoutes,
        setSessionAudioHealthNotice: ctx.setSessionAudioHealthNotice,
  } as InterviewSessionLifecycleDeps;
}

export function syncScoreInterviewDeps(
  ref: MutableRefObject<ScoreInterviewDeps>,
  ctx: AriaInterviewDepsSyncContext,
): void {
  ref.current = {
    userId: ctx.userId,
        isAdmin: ctx.isAdmin,
        typologyContext: ctx.typologyContext,
        routeName: ctx.routeName,
        userEmail: ctx.userEmail,
        profile: ctx.profile,
        fromValidationTrack: ctx.fromValidationTrack,
        navigation: ctx.navigation,
        queryClient: ctx.queryClient,
        saveInterviewResults: ctx.saveInterviewResults,
        ensureValidSession: ctx.ensureValidSession,
        scoreScenario: ctx.scoreScenario,
        setScenarioScores: ctx.setScenarioScores,
        setResults: ctx.setResults,
        setStageResults: ctx.setStageResults,
        setInterviewStatus: ctx.setInterviewStatus,
        setStatus: ctx.setStatus,
        setPendingScoringSyncAttemptId: ctx.setPendingScoringSyncAttemptId,
        loadEmotionResponsesForCompletion: ctx.loadEmotionResponsesForCompletion,
        applyEmotionResponsesToSession: ctx.applyEmotionResponsesToSession,
        markCompletionScoringInFlight: ctx.markCompletionScoringInFlight,
        replaceWithStandardApplicantPostInterviewHandoffForUser: ctx.replaceWithStandardApplicantPostInterviewHandoffForUser,
        setInterviewLastCommittedAttemptId: ctx.setInterviewLastCommittedAttemptId,
        scoreInterviewInFlightRef: ctx.scoreInterviewInFlightRef,
        scoreInterviewAttemptedRef: ctx.scoreInterviewAttemptedRef,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        interviewSessionIdRef: ctx.interviewSessionIdRef,
        interviewStatusRef: ctx.interviewStatusRef,
        emotionItemResponsesRef: ctx.emotionItemResponsesRef,
        scenarioScoresRef: ctx.scenarioScoresRef,
        scoredScenariosRef: ctx.scoredScenariosRef,
        moment4SpecificityScoringRef: ctx.moment4SpecificityScoringRef,
        moment5ClientScoringMetaRef: ctx.moment5ClientScoringMetaRef,
        moment5AccountabilityProbeFiredRef: ctx.moment5AccountabilityProbeFiredRef,
        probeLogRef: ctx.probeLogRef,
        responseTimingsRef: ctx.responseTimingsRef,
        scenarioSkipConfirmedCountRef: ctx.scenarioSkipConfirmedCountRef,
        deferredMoment4NarrativeRef: ctx.deferredMoment4NarrativeRef,
        setReasoningProgress: ctx.setReasoningProgress,
        setAnalysisAttemptId: ctx.setAnalysisAttemptId,
  } as ScoreInterviewDeps;
}

export function syncAriaInterviewLifecycleDeps(
  refs: Pick<AriaInterviewDepsRefs, 'sessionLifecycleDepsRef' | 'scoreInterviewDepsRef'>,
  ctx: AriaInterviewDepsSyncContext,
): void {
  syncSessionLifecycleDeps(refs.sessionLifecycleDepsRef, ctx);
  syncScoreInterviewDeps(refs.scoreInterviewDepsRef, ctx);
}
