import type { ClaudeParallelStreamTtsCallDeps } from '@features/aria/claudeParallelStreamTtsCallTypes';
import type { EmotionModalOrchestrationDeps } from '@features/aria/emotionModalOrchestrationTypes';
import type { InterviewWebTtsRuntimeDeps } from '@features/aria/hooks/useInterviewWebTtsRuntime';
import type { SpeakTextSafeDeps } from '@features/aria/speakTextSafeDeps';
import type {
  AriaInterviewDepsRefs,
  AriaInterviewDepsSyncContext,
} from '@features/aria/syncAriaInterviewDepsTypes';

export function syncAriaInterviewEarlyDeps(
  refs: Pick<AriaInterviewDepsRefs, 'emotionModalOrchestrationDepsRef' | 'webTtsRuntimeDepsRef'>,
  ctx: AriaInterviewDepsSyncContext,
): void {
  refs.emotionModalOrchestrationDepsRef.current = {
    userId: ctx.userId,
        isAdmin: ctx.isAdmin,
        isInterviewAppRoute: ctx.isInterviewAppRoute,
        emotionItemsComplete: ctx.emotionItemsComplete,
        status: ctx.status,
        voiceState: ctx.voiceState,
        emotionModalVisible: ctx.emotionModalVisible,
        emotionModalItemIndex: ctx.emotionModalItemIndex,
        statusRef: ctx.statusRef,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        emotionItemResponsesRef: ctx.emotionItemResponsesRef,
        emotionModalResolveRef: ctx.emotionModalResolveRef,
        emotionModalPendingTransitionRef: ctx.emotionModalPendingTransitionRef,
        emotionModalOpenForIndexRef: ctx.emotionModalOpenForIndexRef,
        emotionModalTimeoutRef: ctx.emotionModalTimeoutRef,
        emotionModalShownForScenarioRef: ctx.emotionModalShownForScenarioRef,
        pendingEmotionModalTransitionRef: ctx.pendingEmotionModalTransitionRef,
        maybeAwaitEmotionAfterScenarioTransitionRef: ctx.maybeAwaitEmotionAfterScenarioTransitionRef,
        runEmotionModalAfterScenarioTransitionRef: ctx.runEmotionModalAfterScenarioTransitionRef,
        tryRunEmotionModalFromScenarioTransitionRef: ctx.tryRunEmotionModalFromScenarioTransitionRef,
        setEmotionItemResponses: ctx.setEmotionItemResponses,
        setEmotionItemsComplete: ctx.setEmotionItemsComplete,
        setEmotionModalVisible: ctx.setEmotionModalVisible,
        setEmotionModalItemIndex: ctx.setEmotionModalItemIndex,
        waitForWebInterviewTtsQuiescentBeforeEmotionModal: ctx.waitForWebInterviewTtsQuiescentBeforeEmotionModal,
        waitForWebInterviewTtsAudiblePlaybackBeforeEmotionModal:
          ctx.waitForWebInterviewTtsAudiblePlaybackBeforeEmotionModal,
  } as EmotionModalOrchestrationDeps;

  refs.webTtsRuntimeDepsRef.current = {
    voiceStateRef: ctx.voiceStateRef,
        setVoiceState: ctx.setVoiceState,
        parallelStreamingTtsRef: ctx.parallelStreamingTtsRef,
        ttsLineInFlightRef: ctx.ttsLineInFlightRef,
        webTabRestoreReplayInFlightRef: ctx.webTabRestoreReplayInFlightRef,
        webTtsTabInterruptPendingReplayRef: ctx.webTtsTabInterruptPendingReplayRef,
        webTtsSpeakGenerationRef: ctx.webTtsSpeakGenerationRef,
        webTtsUtteranceInFlightRef: ctx.webTtsUtteranceInFlightRef,
        webTtsUtteranceInFlightOptionsRef: ctx.webTtsUtteranceInFlightOptionsRef,
        pendingGestureRestoreSpeakRef: ctx.pendingGestureRestoreSpeakRef,
        mobileTabHideLetPlaybackContinueRef: ctx.mobileTabHideLetPlaybackContinueRef,
        mobileTabHideBackgroundUtteranceRef: ctx.mobileTabHideBackgroundUtteranceRef,
        tabHiddenDuringActiveTtsLineRef: ctx.tabHiddenDuringActiveTtsLineRef,
        needsGestureRestoreRef: ctx.needsGestureRestoreRef,
        tabVisibilityGestureLossPendingRef: ctx.tabVisibilityGestureLossPendingRef,
        lastQuestionTextRef: ctx.lastQuestionTextRef,
        setWebTabRestoreOverlayVisible: ctx.setWebTabRestoreOverlayVisible,
        ensureWebGestureFlushListener: ctx.ensureWebGestureFlushListener,
  } as InterviewWebTtsRuntimeDeps;

}

export function syncAriaInterviewTtsPipelineDeps(
  refs: Pick<AriaInterviewDepsRefs, 'speakTextSafeDepsRef' | 'claudeParallelStreamTtsDepsRef'>,
  ctx: AriaInterviewDepsSyncContext,
): void {
  refs.speakTextSafeDepsRef.current = {
    userId: ctx.userId,
        mobileWebTapToBeginDone: ctx.mobileWebTapToBeginDone,
        setVoiceState: ctx.setVoiceState,
        setWebTabGestureRestoreOverlay: ctx.setWebTabGestureRestoreOverlay,
        setWebDesktopPendingTtsGestureOverlay: ctx.setWebDesktopPendingTtsGestureOverlay,
        setTtsPlaybackReliabilityNotice: ctx.setTtsPlaybackReliabilityNotice,
        setLastTtsCompletionCallbackMs: ctx.setLastTtsCompletionCallbackMs,
        speak: ctx.speak,
        applyInterviewSpeechComplete: ctx.applyInterviewSpeechComplete,
        ensureWebGestureFlushListener: ctx.ensureWebGestureFlushListener,
        awaitTtsScreenReadyGate: ctx.awaitTtsScreenReadyGate,
        stopElevenLabsPlayback: ctx.stopElevenLabsPlayback,
        webSpeechShouldDeferToUserGesture: ctx.webSpeechShouldDeferToUserGesture,
        rearmWebMicPreInitAfterTtsPlaybackComplete: ctx.rearmWebMicPreInitAfterTtsPlaybackComplete,
        scheduleWebMicPreInitRefreshAfterTtsCompletes: ctx.scheduleWebMicPreInitRefreshAfterTtsCompletes,
        referenceCardShouldUpdateOnPlaybackStart: ctx.referenceCardShouldUpdateOnPlaybackStart,
        persistInterviewAttemptSessionLifecycle: ctx.persistInterviewAttemptSessionLifecycle,
        webTtsSpeakGenerationRef: ctx.webTtsSpeakGenerationRef,
        currentInterviewMomentRef: ctx.currentInterviewMomentRef,
        currentScenarioRef: ctx.currentScenarioRef,
        s2RepairProbeDeliveredRef: ctx.s2RepairProbeDeliveredRef,
        s3RepairProbeDeliveredRef: ctx.s3RepairProbeDeliveredRef,
        interviewNameRef: ctx.interviewNameRef,
        lastSuccessfulTtsTextNormalizedRef: ctx.lastSuccessfulTtsTextNormalizedRef,
        lastSuccessfulTtsDeliveredPreviewRef: ctx.lastSuccessfulTtsDeliveredPreviewRef,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        interviewSessionIdRef: ctx.interviewSessionIdRef,
        scenarioAContemptProbePlaybackConfirmedRef: ctx.scenarioAContemptProbePlaybackConfirmedRef,
        showScenarioCardCanonicalPlaybackConfirmedKindsRef:
          ctx.showScenarioCardCanonicalPlaybackConfirmedKindsRef,
        scenarioAContemptProbeTtsDeliveredSessionRef: ctx.scenarioAContemptProbeTtsDeliveredSessionRef,
        lastQuestionTextRef: ctx.lastQuestionTextRef,
        ttsLineInFlightRef: ctx.ttsLineInFlightRef,
        needsGestureRestoreRef: ctx.needsGestureRestoreRef,
        tabVisibilityGestureLossPendingRef: ctx.tabVisibilityGestureLossPendingRef,
        gestureContextLostAtRef: ctx.gestureContextLostAtRef,
        webTtsTabInterruptPendingReplayRef: ctx.webTtsTabInterruptPendingReplayRef,
        pendingGestureRestoreSpeakRef: ctx.pendingGestureRestoreSpeakRef,
        interviewStatusRef: ctx.interviewStatusRef,
        applyReferenceCardFromAssistantSpeechRef: ctx.applyReferenceCardFromAssistantSpeechRef,
        recordingJustFinishedBeforeNextTtsRef: ctx.recordingJustFinishedBeforeNextTtsRef,
        postRecordingParallelStreamSettleRef: ctx.postRecordingParallelStreamSettleRef,
        tabHiddenDuringActiveTtsLineRef: ctx.tabHiddenDuringActiveTtsLineRef,
        webTtsUtteranceInFlightRef: ctx.webTtsUtteranceInFlightRef,
        webTtsUtteranceInFlightOptionsRef: ctx.webTtsUtteranceInFlightOptionsRef,
        firstScenarioLifecyclePersistedRef: ctx.firstScenarioLifecyclePersistedRef,
        ttsSessionHardFailureCountRef: ctx.ttsSessionHardFailureCountRef,
        timingRef: ctx.timingRef,
        pendingWebSpeechForGestureRef: ctx.pendingWebSpeechForGestureRef,
        recordInterviewAssistantDeliveryForMetaExemptionRef: ctx.recordInterviewAssistantDeliveryForMetaExemptionRef,
        s1ContemptFixVersion: ctx.s1ContemptFixVersion,
  } as SpeakTextSafeDeps;

  refs.claudeParallelStreamTtsDepsRef.current = {
    userId: ctx.userId,
        recordingJustFinishedBeforeNextTtsRef: ctx.recordingJustFinishedBeforeNextTtsRef,
        postRecordingParallelStreamSettleRef: ctx.postRecordingParallelStreamSettleRef,
        pendingScenarioAContemptProbeStreamMuteRef: ctx.pendingScenarioAContemptProbeStreamMuteRef,
        pendingS3ToM4HandoffStreamMuteRef: ctx.pendingS3ToM4HandoffStreamMuteRef,
        parallelStreamingTtsRef: ctx.parallelStreamingTtsRef,
        webTtsSpeakGenerationRef: ctx.webTtsSpeakGenerationRef,
        webTtsTabInterruptPendingReplayRef: ctx.webTtsTabInterruptPendingReplayRef,
        webTtsUtteranceInFlightRef: ctx.webTtsUtteranceInFlightRef,
        webTtsUtteranceInFlightOptionsRef: ctx.webTtsUtteranceInFlightOptionsRef,
        ttsLineInFlightRef: ctx.ttsLineInFlightRef,
        pendingGestureRestoreSpeakRef: ctx.pendingGestureRestoreSpeakRef,
        currentInterviewMomentRef: ctx.currentInterviewMomentRef,
        currentScenarioRef: ctx.currentScenarioRef,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        interviewSessionIdRef: ctx.interviewSessionIdRef,
        interviewNameRef: ctx.interviewNameRef,
        s2RepairProbeDeliveredRef: ctx.s2RepairProbeDeliveredRef,
        s3RepairProbeDeliveredRef: ctx.s3RepairProbeDeliveredRef,
        scenarioAContemptProbeAskedRef: ctx.scenarioAContemptProbeAskedRef,
        scenarioAContemptProbePlaybackConfirmedRef: ctx.scenarioAContemptProbePlaybackConfirmedRef,
        scenarioAContemptProbeTtsDeliveredSessionRef: ctx.scenarioAContemptProbeTtsDeliveredSessionRef,
        showScenarioCardCanonicalPlaybackConfirmedKindsRef:
          ctx.showScenarioCardCanonicalPlaybackConfirmedKindsRef,
        scenarioARepairQuestionAskedRef: ctx.scenarioARepairQuestionAskedRef,
        moment5PostPromptUserTurnCountRef: ctx.moment5PostPromptUserTurnCountRef,
        moment5QuestionDeliveredRef: ctx.moment5QuestionDeliveredRef,
        moment5PrimaryAnchorDeliveredSessionRef: ctx.moment5PrimaryAnchorDeliveredSessionRef,
        moment5AccountabilityProbeFiredRef: ctx.moment5AccountabilityProbeFiredRef,
        moment5ResolutionDeliveredRef: ctx.moment5ResolutionDeliveredRef,
        scenarioScoresRef: ctx.scenarioScoresRef,
        moment5ClientScoringMetaRef: ctx.moment5ClientScoringMetaRef,
        moment4ClientSpecificityProbeInjectedRef: ctx.moment4ClientSpecificityProbeInjectedRef,
        moment5SpecificityRedirectIssuedRef: ctx.moment5SpecificityRedirectIssuedRef,
        elongatingProbeFiredRef: ctx.elongatingProbeFiredRef,
        lastQuestionTextRef: ctx.lastQuestionTextRef,
        committedScenarioRef: ctx.committedScenarioRef,
        recordInterviewAssistantDeliveryForMetaExemptionRef: ctx.recordInterviewAssistantDeliveryForMetaExemptionRef,
        applyReferenceCardFromAssistantSpeechRef: ctx.applyReferenceCardFromAssistantSpeechRef,
        speakTextSafe: ctx.speakTextSafe,
        setVoiceState: ctx.setVoiceState,
        setWebTabGestureRestoreOverlay: ctx.setWebTabGestureRestoreOverlay,
        setReferenceCardPrompt: ctx.setReferenceCardPrompt,
        setReferenceCardScenario: ctx.setReferenceCardScenario,
        setInterviewUiPhase: ctx.setInterviewUiPhase,
        awaitTtsScreenReadyGate: ctx.awaitTtsScreenReadyGate,
        prepareInterviewTtsPlayback: ctx.prepareInterviewTtsPlayback,
        stopElevenLabsPlayback: ctx.stopElevenLabsPlayback,
        scheduleWebMicPreInitRefreshAfterTtsCompletes: ctx.scheduleWebMicPreInitRefreshAfterTtsCompletes,
        referenceCardShouldUpdateOnPlaybackStart: ctx.referenceCardShouldUpdateOnPlaybackStart,
        ensureCompletedScenarioScored: ctx.ensureCompletedScenarioScored,
  } as ClaudeParallelStreamTtsCallDeps;

}
