import type { TranscribeSafeDeps } from '@features/aria/transcribeSafeTypes';
import type { AriaInterviewAudioRecorderDeps } from '@features/aria/hooks/useAriaInterviewAudioRecorder';
import type { InterviewMicLifecycleDeps } from '@features/aria/hooks/interviewMicLifecycleTypes';
import type { HandleNativeOrWhisperMicPressDeps } from '@features/aria/handleNativeOrWhisperMicPressTypes';
import type {
  AriaInterviewDepsRefs,
  AriaInterviewDepsSyncContext,
} from '@features/aria/syncAriaInterviewDepsTypes';

export function syncAriaInterviewMicPipelineDeps(
  refs: Pick<AriaInterviewDepsRefs, 'transcribeSafeDepsRef' | 'audioRecorderDepsRef' | 'micLifecycleDepsRef' | 'handleNativeOrWhisperMicPressDepsRef'>,
  ctx: AriaInterviewDepsSyncContext,
): void {
  refs.transcribeSafeDepsRef.current = {
    userId: ctx.userId,
        classifyError: ctx.classifyError,
        transcribeBufferMetaRef: ctx.transcribeBufferMetaRef,
        currentInterviewMomentRef: ctx.currentInterviewMomentRef,
        recordingPeakMeteringRef: ctx.recordingPeakMeteringRef,
        lastRecordingVadSpeechDetectedRef: ctx.lastRecordingVadSpeechDetectedRef,
        lastQuestionTextRef: ctx.lastQuestionTextRef,
        transcriptionFailureStreakRef: ctx.transcriptionFailureStreakRef,
        lastRecordingRetryDeliveredNormRef: ctx.lastRecordingRetryDeliveredNormRef,
        recordingJustFinishedBeforeNextTtsRef: ctx.recordingJustFinishedBeforeNextTtsRef,
        postRecordingParallelStreamSettleRef: ctx.postRecordingParallelStreamSettleRef,
        deleteTurnAudioFile: ctx.deleteTurnAudioFile,
        deliverRecordingRetryLine: ctx.deliverRecordingRetryLine,
  } as TranscribeSafeDeps;

  refs.audioRecorderDepsRef.current = {
    userId: ctx.userId,
        isInterviewAppRoute: ctx.isInterviewAppRoute,
        useMediaRecorderPath: ctx.useMediaRecorderPath,
        messages: ctx.messages,
        recordingCompleteInFlightRef: ctx.recordingCompleteInFlightRef,
        recordingPeakMeteringRef: ctx.recordingPeakMeteringRef,
        lastRecordingVadSpeechDetectedRef: ctx.lastRecordingVadSpeechDetectedRef,
        recordingJustFinishedBeforeNextTtsRef: ctx.recordingJustFinishedBeforeNextTtsRef,
        postRecordingParallelStreamSettleRef: ctx.postRecordingParallelStreamSettleRef,
        micTapWhileTtsActiveRef: ctx.micTapWhileTtsActiveRef,
        consecutiveDigitalSilenceForMicFallbackRef: ctx.consecutiveDigitalSilenceForMicFallbackRef,
        micFallbackSuccessPendingRef: ctx.micFallbackSuccessPendingRef,
        pendingRecordingRestartAfterVadBypassRef: ctx.pendingRecordingRestartAfterVadBypassRef,
        transcribeBufferMetaRef: ctx.transcribeBufferMetaRef,
        whisperRatioReaskAttemptsForCurrentQuestionRef: ctx.whisperRatioReaskAttemptsForCurrentQuestionRef,
        interviewSessionIdRef: ctx.interviewSessionIdRef,
        metaCommentAckAwaitingSubstantiveBaselineSeqRef: ctx.metaCommentAckAwaitingSubstantiveBaselineSeqRef,
        substantiveInterviewQuestionDeliveredSeqRef: ctx.substantiveInterviewQuestionDeliveredSeqRef,
        recoveryAssistantSpokenAtSubstantiveSeqRef: ctx.recoveryAssistantSpokenAtSubstantiveSeqRef,
        lastVoiceTurnLanguageRef: ctx.lastVoiceTurnLanguageRef,
        lastVoiceTurnConfidenceRef: ctx.lastVoiceTurnConfidenceRef,
        turnAudioIndexRef: ctx.turnAudioIndexRef,
        lastUserTurnAudioDurationMsRef: ctx.lastUserTurnAudioDurationMsRef,
        interviewNameRef: ctx.interviewNameRef,
        interviewNameReaskPendingRef: ctx.interviewNameReaskPendingRef,
        lastQuestionTextRef: ctx.lastQuestionTextRef,
        currentInterviewMomentRef: ctx.currentInterviewMomentRef,
        currentScenarioRef: ctx.currentScenarioRef,
        releaseRecordingFnRef: ctx.releaseRecordingFnRef,
        audioRecorder: {
          getLastWebMicCaptureDeviceId: () => ctx.audioRecorder.getLastWebMicCaptureDeviceId() ?? null,
          switchWebInputToDefaultDevice: () => ctx.audioRecorder.switchWebInputToDefaultDevice(),
        },
        setMicEnginePrimed: ctx.setMicEnginePrimed,
        setVoiceState: ctx.setVoiceState,
        setMessages: ctx.setMessages,
        deleteTurnAudioFile: ctx.deleteTurnAudioFile,
        deliverRecordingRetryLine: ctx.deliverRecordingRetryLine,
        transcribeSafe: ctx.transcribeSafe,
        speakTextSafe: ctx.speakTextSafe,
        processTurnAudioWithRetry: ctx.processTurnAudioWithRetry,
        processUserSpeech: ctx.processUserSpeech,
        interviewStatusRef: ctx.interviewStatusRef,
        resumeLoadingFlowActiveRef: ctx.resumeLoadingFlowActiveRef,
        webResumeWelcomeTapPendingRef: ctx.webResumeWelcomeTapPendingRef,
        resumeOfferWelcomeTtsRef: ctx.resumeOfferWelcomeTtsRef,
        resumeRepeatChoicePendingRef: ctx.resumeRepeatChoicePendingRef,
        webResumeWelcomeTapHandledRef: ctx.webResumeWelcomeTapHandledRef,
        interviewUserTurnEpochRef: ctx.interviewUserTurnEpochRef,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        applyRouteProbeAfterResume: ctx.applyRouteProbeAfterResume,
        setMicNeedsReconnect: ctx.setMicNeedsReconnect,
        recordingDelayMeasurementRef: ctx.recordingDelayMeasurementRef,
        handleRecordingError: ctx.handleRecordingError,
  } as AriaInterviewAudioRecorderDeps;

  refs.micLifecycleDepsRef.current = {
    navigation: ctx.navigation,
        userId: ctx.userId,
        userIdRef: ctx.userIdRef,
        voiceState: ctx.voiceState,
        interviewStatus: ctx.interviewStatus,
        interviewStatusRef: ctx.interviewStatusRef,
        useMediaRecorderPath: ctx.useMediaRecorderPath,
        audioRecorder: ctx.audioRecorder,
        applyRouteProbeAfterResume: ctx.applyRouteProbeAfterResume,
        setMicSessionRecovering: ctx.setMicSessionRecovering,
        setMicNeedsReconnect: ctx.setMicNeedsReconnect,
        setLateStartIdleCueVisible: ctx.setLateStartIdleCueVisible,
        setPreInitMeterLevel: ctx.setPreInitMeterLevel,
        setVoiceState: ctx.setVoiceState,
        setEmotionModalVisible: ctx.setEmotionModalVisible,
        setWebTabRestoreOverlayVisible: ctx.setWebTabRestoreOverlayVisible,
        gestureContextLostAtRef: ctx.gestureContextLostAtRef,
        recognitionRef: ctx.recognitionRef,
        parallelStreamingTtsRef: ctx.parallelStreamingTtsRef,
        webTtsSpeakGenerationRef: ctx.webTtsSpeakGenerationRef,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        interviewSessionIdRef: ctx.interviewSessionIdRef,
        currentInterviewMomentRef: ctx.currentInterviewMomentRef,
        currentScenarioRef: ctx.currentScenarioRef,
        lastQuestionTextRef: ctx.lastQuestionTextRef,
        emotionModalPendingTransitionRef: ctx.emotionModalPendingTransitionRef,
        pendingGestureRestoreSpeakRef: ctx.pendingGestureRestoreSpeakRef,
        webTtsTabInterruptPendingReplayRef: ctx.webTtsTabInterruptPendingReplayRef,
        mobileTabHideLetPlaybackContinueRef: ctx.mobileTabHideLetPlaybackContinueRef,
        needsGestureRestoreRef: ctx.needsGestureRestoreRef,
        syncInterviewTtsAfterScreenReturn: ctx.syncInterviewTtsAfterScreenReturn,
        dismissTabRestoreOverlay: ctx.dismissTabRestoreOverlay,
        ensureWebGestureFlushListener: ctx.ensureWebGestureFlushListener,
        interruptAllWebInterviewTtsOutput: ctx.interruptAllWebInterviewTtsOutput,
        stopElevenLabsPlayback: ctx.stopElevenLabsPlayback,
        isWebInterviewPlaybackAudiblyActive: ctx.isWebInterviewPlaybackAudiblyActive,
        armMobileWebBackgroundTtsContinue: ctx.armMobileWebBackgroundTtsContinue,
        isMobileWebInterviewTtsSessionActive: ctx.isMobileWebInterviewTtsSessionActive,
        hasWebInterviewHtmlAudioTabResumePending: ctx.hasWebInterviewHtmlAudioTabResumePending,
        holdTabStashedHtmlAudioForGestureResume: ctx.holdTabStashedHtmlAudioForGestureResume,
        hasInterviewClosingSpeakInFlightForSession: ctx.hasInterviewClosingSpeakInFlightForSession,
        classifyInterviewQuestionType: ctx.classifyInterviewQuestionType,
  } as InterviewMicLifecycleDeps;

  refs.handleNativeOrWhisperMicPressDepsRef.current = {
    userId: ctx.userId,
        voiceState: ctx.voiceState,
        useTapMicUi: ctx.useTapMicUi,
        useMediaRecorderPath: ctx.useMediaRecorderPath,
        audioRecorder: ctx.audioRecorder,
        touchActivity: ctx.touchActivity,
        setSessionAudioHealthNotice: ctx.setSessionAudioHealthNotice,
        setConversationErrorNotice: ctx.setConversationErrorNotice,
        resumeRepeatChoicePendingRef: ctx.resumeRepeatChoicePendingRef,
        currentMessagesRef: ctx.currentMessagesRef,
        resumeLastAssistantTextRef: ctx.resumeLastAssistantTextRef,
        lastQuestionTextRef: ctx.lastQuestionTextRef,
        handleRecordingError: ctx.handleRecordingError,
        isInterviewerOutputActiveForMicGate: ctx.isInterviewerOutputActiveForMicGate,
        voiceStateRef: ctx.voiceStateRef,
        setVoiceState: ctx.setVoiceState,
        mobileTabHideLetPlaybackContinueRef: ctx.mobileTabHideLetPlaybackContinueRef,
        webMicArmInFlightRef: ctx.webMicArmInFlightRef,
        webTabGestureRestoreOverlayRef: ctx.webTabGestureRestoreOverlayRef,
        webTtsTabInterruptPendingReplayRef: ctx.webTtsTabInterruptPendingReplayRef,
        webTabRestoreReplayInFlightRef: ctx.webTabRestoreReplayInFlightRef,
        pendingGestureRestoreSpeakRef: ctx.pendingGestureRestoreSpeakRef,
        handleWebTabGestureRestoreTapRef: ctx.handleWebTabGestureRestoreTapRef,
        setWebTabGestureRestoreOverlay: ctx.setWebTabGestureRestoreOverlay,
        ensureWebGestureFlushListener: ctx.ensureWebGestureFlushListener,
        pendingMicStartAfterIdleFlushRef: ctx.pendingMicStartAfterIdleFlushRef,
        startRecordingAfterPendingTts: ctx.startRecordingAfterPendingTts,
        pendingWebSpeechForGestureRef: ctx.pendingWebSpeechForGestureRef,
        webGestureTtsConsumedPressRef: ctx.webGestureTtsConsumedPressRef,
        webGestureConsumeClearTimeoutRef: ctx.webGestureConsumeClearTimeoutRef,
        handlePressEnd: ctx.handlePressEnd,
        handlePressStart: ctx.handlePressStart,
        waitUntilInterviewerQuiescentForWebMic: ctx.waitUntilInterviewerQuiescentForWebMic,
        ttsLineInFlightRef: ctx.ttsLineInFlightRef,
        interviewNameRef: ctx.interviewNameRef,
        interviewNameReaskPendingRef: ctx.interviewNameReaskPendingRef,
        micTapWhileTtsActiveRef: ctx.micTapWhileTtsActiveRef,
        setMicEnginePrimed: ctx.setMicEnginePrimed,
        recordingDelayMeasurementRef: ctx.recordingDelayMeasurementRef,
        lastHeadphoneProbeRef: ctx.lastHeadphoneProbeRef,
        lastAudioRouteFingerprintRef: ctx.lastAudioRouteFingerprintRef,
        currentInterviewMomentRef: ctx.currentInterviewMomentRef,
        currentScenarioRef: ctx.currentScenarioRef,
        resumeRepeatPrefetchMpegRef: ctx.resumeRepeatPrefetchMpegRef,
        takeRecordingStartEventDataWithVadBypassRestart: ctx.takeRecordingStartEventDataWithVadBypassRestart,
        isWebInterviewPlaybackAudiblyActive: ctx.isWebInterviewPlaybackAudiblyActive,
        webSpeechShouldDeferToUserGesture: ctx.webSpeechShouldDeferToUserGesture,
  } as HandleNativeOrWhisperMicPressDeps;

}
