import type { MutableRefObject } from 'react';

import type { ClaudeParallelStreamTtsCallDeps } from '@features/aria/claudeParallelStreamTtsCallTypes';
import type { KickPostClosingInterviewCompletionDeps } from '@features/aria/hooks/useKickPostClosingInterviewCompletion';
import type { ScoreScenarioDeps } from '@features/aria/scoreScenarioTypes';
import type { PostClaudeAssistantTurnDeps } from '@features/aria/postClaudeAssistantTurnTypes';
import type { PreClaudeTurnGateDeps } from '@features/aria/preClaudeTurnGateTypes';
import type { ProcessUserSpeechDeps } from '@features/aria/processUserSpeechTypes';
import type {
  AriaInterviewDepsRefs,
  AriaInterviewDepsSyncContext,
} from '@features/aria/syncAriaInterviewDepsTypes';
import { mergeAriaInterviewSyncCtx } from '@features/aria/syncAriaInterviewDepsTypes';

export type ProcessUserSpeechDepRefs = {
  preClaudeTurnGateDepsRef: MutableRefObject<PreClaudeTurnGateDeps>;
  claudeParallelStreamTtsDepsRef: MutableRefObject<ClaudeParallelStreamTtsCallDeps>;
  postClaudeTurnDepsRef: MutableRefObject<PostClaudeAssistantTurnDeps>;
};

export function syncAriaInterviewTurnHandlerDeps(
  refs: Pick<AriaInterviewDepsRefs, 'kickPostClosingCompletionDepsRef' | 'scoreScenarioDepsRef' | 'postClaudeTurnDepsRef' | 'preClaudeTurnGateDepsRef'>,
  ctx: AriaInterviewDepsSyncContext,
): void {
  refs.kickPostClosingCompletionDepsRef.current = {
    userId: ctx.userId,
        isAdmin: ctx.isAdmin,
        isInterviewAppRoute: ctx.isInterviewAppRoute,
        status: ctx.status,
        setVoiceState: ctx.setVoiceState,
        setInterviewStatus: ctx.setInterviewStatus,
        setPendingCompletion: ctx.setPendingCompletion,
        setIsWaiting: ctx.setIsWaiting,
        setPendingScoringSyncAttemptId: ctx.setPendingScoringSyncAttemptId,
        isInterviewCompleteRef: ctx.isInterviewCompleteRef,
        interviewMomentsCompleteRef: ctx.interviewMomentsCompleteRef,
        currentInterviewMomentRef: ctx.currentInterviewMomentRef,
        pendingCompletionTranscriptRef: ctx.pendingCompletionTranscriptRef,
        scoredScenariosRef: ctx.scoredScenariosRef,
        scenarioScoresRef: ctx.scenarioScoresRef,
        resumeActiveScenarioRef: ctx.resumeActiveScenarioRef,
        emotionItemResponsesRef: ctx.emotionItemResponsesRef,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        interviewSessionIdRef: ctx.interviewSessionIdRef,
        interviewStatusRef: ctx.interviewStatusRef,
        kickCompletionScoring: ctx.kickCompletionScoring,
        awaitEmotionModalForIndex: ctx.awaitEmotionModalForIndex,
        listUnansweredEmotionModalIndices: ctx.listUnansweredEmotionModalIndices,
  } as KickPostClosingInterviewCompletionDeps;

  refs.scoreScenarioDepsRef.current = {
    userId: ctx.userId,
        isAdmin: ctx.isAdmin,
        scoredScenariosRef: ctx.scoredScenariosRef,
        scenarioCRepairOnlyEvidenceRef: ctx.scenarioCRepairOnlyEvidenceRef,
        scenarioScoresRef: ctx.scenarioScoresRef,
        scenarioFrustrationSkipNullMarkersRef: ctx.scenarioFrustrationSkipNullMarkersRef,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        probeLogRef: ctx.probeLogRef,
        setScenarioScores: ctx.setScenarioScores,
        setMessages: ctx.setMessages,
        saveScenarioCheckpoint: ctx.saveScenarioCheckpoint,
  } as ScoreScenarioDeps;

  refs.postClaudeTurnDepsRef.current = {
    userId: ctx.userId,
        isAdmin: ctx.isAdmin,
        isInterviewAppRoute: ctx.isInterviewAppRoute,
        status: ctx.status,
        setVoiceState: ctx.setVoiceState,
        setIsWaiting: ctx.setIsWaiting,
        setMessages: ctx.setMessages,
        setInterviewStatus: ctx.setInterviewStatus,
        setPendingCompletion: ctx.setPendingCompletion,
        setReferenceCardPrompt: ctx.setReferenceCardPrompt,
        setReferenceCardScenario: ctx.setReferenceCardScenario,
        setInterviewUiPhase: ctx.setInterviewUiPhase,
        committedScenarioRef: ctx.committedScenarioRef,
        showScenarioCardCanonicalPlaybackConfirmedKindsRef:
          ctx.showScenarioCardCanonicalPlaybackConfirmedKindsRef,
        setHighestScenarioReached: ctx.setHighestScenarioReached,
        fetchStageScore: ctx.fetchStageScore,
        setStageResults: ctx.setStageResults,
        setClosingQuestionPending: ctx.setClosingQuestionPending,
        setClosingQuestionScenario: ctx.setClosingQuestionScenario,
        setClosingQuestionState: ctx.setClosingQuestionState,
        setTouchedConstructs: ctx.setTouchedConstructs,
        commitInterviewMessages: ctx.commitInterviewMessages,
        speakTextSafe: ctx.speakTextSafe,
        applyInterviewSpeechComplete: ctx.applyInterviewSpeechComplete,
        kickPostClosingInterviewCompletionIfReady: ctx.kickPostClosingInterviewCompletionIfReady,
        kickCompletionScoring: ctx.kickCompletionScoring,
        awaitEmotionModalForIndex: ctx.awaitEmotionModalForIndex,
        listUnansweredEmotionModalIndices: ctx.listUnansweredEmotionModalIndices,
        runEmotionModalAfterScenarioTransition: ctx.runEmotionModalAfterScenarioTransition,
        scoreScenario: ctx.scoreScenario,
        notifyScenarioStarted: ctx.notifyScenarioStarted,
        ensureCompletedScenarioScored: ctx.ensureCompletedScenarioScored,
        markClosingQuestionAsked: ctx.markClosingQuestionAsked,
        markClosingQuestionAnswered: ctx.markClosingQuestionAnswered,
        resolveAssistantScenarioNumber: ctx.resolveAssistantScenarioNumber,
        applyInterviewProgressFromAssistantText: ctx.applyInterviewProgressFromAssistantText,
        finalizePendingMetaAckBaselineAfterAssistantTextRef: ctx.finalizePendingMetaAckBaselineAfterAssistantTextRef,
        insertPreambleBriefingIfMissing: ctx.insertPreambleBriefingIfMissing,
        persistInterviewAttemptSessionLifecycle: ctx.persistInterviewAttemptSessionLifecycle,
        saveInterviewProgress: ctx.saveInterviewProgress,
        markPreparingResultsSession: ctx.markPreparingResultsSession,
        closingQuestionAnsweredRef: ctx.closingQuestionAnsweredRef,
        closingQuestionAskedRef: ctx.closingQuestionAskedRef,
        currentInterviewMomentRef: ctx.currentInterviewMomentRef,
        currentMessagesRef: ctx.currentMessagesRef,
        currentScenarioRef: ctx.currentScenarioRef,
        elongatingProbeFiredRef: ctx.elongatingProbeFiredRef,
        emotionItemResponsesRef: ctx.emotionItemResponsesRef,
        interviewMomentsCompleteRef: ctx.interviewMomentsCompleteRef,
        interviewNameRef: ctx.interviewNameRef,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        interviewSessionIdRef: ctx.interviewSessionIdRef,
        interviewStatusRef: ctx.interviewStatusRef,
        isInterviewCompleteRef: ctx.isInterviewCompleteRef,
        lastAnsweredClosingScenarioRef: ctx.lastAnsweredClosingScenarioRef,
        lastClosingQuestionScenarioRef: ctx.lastClosingQuestionScenarioRef,
        lastQuestionTextRef: ctx.lastQuestionTextRef,
        moment4ClientSpecificityProbeInjectedRef: ctx.moment4ClientSpecificityProbeInjectedRef,
        moment4ThresholdProbeAskedRef: ctx.moment4ThresholdProbeAskedRef,
        deliveredReflectionRegistryRef: ctx.deliveredReflectionRegistryRef,
        moment5AccountabilityProbeFiredRef: ctx.moment5AccountabilityProbeFiredRef,
        moment5ClientScoringMetaRef: ctx.moment5ClientScoringMetaRef,
        moment5ConflictValidityClarificationIssuedRef: ctx.moment5ConflictValidityClarificationIssuedRef,
        moment5PostPromptUserTurnCountRef: ctx.moment5PostPromptUserTurnCountRef,
        moment5PrimaryAnchorDeliveredSessionRef: ctx.moment5PrimaryAnchorDeliveredSessionRef,
        moment5QuestionDeliveredRef: ctx.moment5QuestionDeliveredRef,
        moment5QuestionDeliveryInFlightRef: ctx.moment5QuestionDeliveryInFlightRef,
        parallelStreamingTtsRef: ctx.parallelStreamingTtsRef,
        ttsLineInFlightRef: ctx.ttsLineInFlightRef,
        ttsUtteranceInFlightRef: ctx.ttsUtteranceInFlightRef,
        pendingCompletionTranscriptRef: ctx.pendingCompletionTranscriptRef,
        pendingEmotionModalTransitionRef: ctx.pendingEmotionModalTransitionRef,
        personalHandoffInjectedRef: ctx.personalHandoffInjectedRef,
        resumeActiveScenarioRef: ctx.resumeActiveScenarioRef,
        scenarioAContemptProbeAskedRef: ctx.scenarioAContemptProbeAskedRef,
        scenarioAContemptProbePlaybackConfirmedRef: ctx.scenarioAContemptProbePlaybackConfirmedRef,
        scenarioAContemptProbeTtsDeliveredSessionRef: ctx.scenarioAContemptProbeTtsDeliveredSessionRef,
        scenarioARepairQuestionAskedRef: ctx.scenarioARepairQuestionAskedRef,
        scenarioScoresRef: ctx.scenarioScoresRef,
        scoreInterviewAttemptedRef: ctx.scoreInterviewAttemptedRef,
        scoredScenariosRef: ctx.scoredScenariosRef,
        s2RepairProbeDeliveredRef: ctx.s2RepairProbeDeliveredRef,
        s3RepairProbeDeliveredRef: ctx.s3RepairProbeDeliveredRef,
        scenarioCSophiePerspectiveProbeFiredRef: ctx.scenarioCSophiePerspectiveProbeFiredRef,
        moment5SpecificityRedirectIssuedRef: ctx.moment5SpecificityRedirectIssuedRef,
        moment5ResolutionFollowUpIssuedRef: ctx.moment5ResolutionFollowUpIssuedRef,
        moment5ResolutionDeliveredRef: ctx.moment5ResolutionDeliveredRef,
        recordInterviewAssistantDeliveryForMetaExemptionRef: ctx.recordInterviewAssistantDeliveryForMetaExemptionRef,
        resetScenarioCClientGatesOnly: ctx.resetScenarioCClientGatesOnly,
        setPendingScoringSyncAttemptId: ctx.setPendingScoringSyncAttemptId,
  } as PostClaudeAssistantTurnDeps;

  refs.preClaudeTurnGateDepsRef.current = {
    messages: ctx.messages,
        userId: ctx.userId,
        isAdmin: ctx.isAdmin,
        isInterviewAppRoute: ctx.isInterviewAppRoute,
        status: ctx.status,
        closingQuestionPending: ctx.closingQuestionPending,
        closingQuestionScenario: ctx.closingQuestionScenario,
        usedPersonalExamples: ctx.usedPersonalExamples,
        setVoiceState: ctx.setVoiceState,
        setIsWaiting: ctx.setIsWaiting,
        setMessages: ctx.setMessages,
        setCurrentTranscript: ctx.setCurrentTranscript,
        setExchangeCount: ctx.setExchangeCount,
        setHighestScenarioReached: ctx.setHighestScenarioReached,
        setClosingQuestionPending: ctx.setClosingQuestionPending,
        setClosingQuestionScenario: ctx.setClosingQuestionScenario,
        setInterviewStatus: ctx.setInterviewStatus,
        setPendingCompletion: ctx.setPendingCompletion,
        setResults: ctx.setResults,
        setStatus: ctx.setStatus,
        setTouchedConstructs: ctx.setTouchedConstructs,
        setUsedPersonalExamples: ctx.setUsedPersonalExamples,
        setReferenceCardPrompt: ctx.setReferenceCardPrompt,
        setReferenceCardScenario: ctx.setReferenceCardScenario,
        setInterviewUiPhase: ctx.setInterviewUiPhase,
        committedScenarioRef: ctx.committedScenarioRef,
        showScenarioCardCanonicalPlaybackConfirmedKindsRef:
          ctx.showScenarioCardCanonicalPlaybackConfirmedKindsRef,
        commitInterviewMessages: ctx.commitInterviewMessages,
        speakTextSafe: ctx.speakTextSafe,
        deliverRecordingRetryLine: ctx.deliverRecordingRetryLine,
        invalidateProfileQuery: () => {
          ctx.queryClient.invalidateQueries({ queryKey: ['profile', ctx.userId] });
        },
        applyInterviewProgressFromAssistantText: ctx.applyInterviewProgressFromAssistantText,
        scoreScenario: ctx.scoreScenario,
        notifyScenarioStarted: ctx.notifyScenarioStarted,
        ensureCompletedScenarioScored: ctx.ensureCompletedScenarioScored,
        markClosingQuestionAsked: ctx.markClosingQuestionAsked,
        markClosingQuestionAnswered: ctx.markClosingQuestionAnswered,
        runEmotionModalAfterScenarioTransition: ctx.runEmotionModalAfterScenarioTransition,
        awaitEmotionModalForIndex: ctx.awaitEmotionModalForIndex,
        kickPostClosingInterviewCompletionIfReady: ctx.kickPostClosingInterviewCompletionIfReady,
        kickCompletionScoring: ctx.kickCompletionScoring,
        showChatError: ctx.showChatError,
        createInterviewAttemptOnFirstSubstantiveResponse: ctx.createInterviewAttemptOnFirstSubstantiveResponse,
        collectDeviceContext: ctx.collectDeviceContext,
        resetSessionLogRuntime: ctx.resetSessionLogRuntime,
        assignAttemptIdForSessionLogs: ctx.assignAttemptIdForSessionLogs,
        markAiProcessingTurnStarted: ctx.markAiProcessingTurnStarted,
        metaClassificationForPendingAssistantRef: ctx.metaClassificationForPendingAssistantRef,
        whisperRatioReaskAttemptsForCurrentQuestionRef: ctx.whisperRatioReaskAttemptsForCurrentQuestionRef,
        resumeRepeatChoicePendingRef: ctx.resumeRepeatChoicePendingRef,
        resumeLastAssistantTextRef: ctx.resumeLastAssistantTextRef,
        lastQuestionTextRef: ctx.lastQuestionTextRef,
        parallelStreamingTtsRef: ctx.parallelStreamingTtsRef,
        webTabRestoreDeliveredNormRef: ctx.webTabRestoreDeliveredNormRef,
        ttsLineInFlightRef: ctx.ttsLineInFlightRef,
        ttsUtteranceInFlightRef: ctx.ttsUtteranceInFlightRef,
        interviewSessionIdRef: ctx.interviewSessionIdRef,
        interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
        interviewAttemptCreationInFlightRef: ctx.interviewAttemptCreationInFlightRef,
        interviewNameRef: ctx.interviewNameRef,
        interviewNameReaskPendingRef: ctx.interviewNameReaskPendingRef,
        interviewNameReaskUsedRef: ctx.interviewNameReaskUsedRef,
        interviewStatusRef: ctx.interviewStatusRef,
        currentInterviewMomentRef: ctx.currentInterviewMomentRef,
        currentScenarioRef: ctx.currentScenarioRef,
        currentMessagesRef: ctx.currentMessagesRef,
        transcriptAtReleaseRef: ctx.transcriptAtReleaseRef,
        frustrationSkipOfferPendingRef: ctx.frustrationSkipOfferPendingRef,
        frustrationSkipAwaitingConfirmationRef: ctx.frustrationSkipAwaitingConfirmationRef,
        frustrationSkipHadPriorAnswerRef: ctx.frustrationSkipHadPriorAnswerRef,
        scenarioSkipOfferSourceRef: ctx.scenarioSkipOfferSourceRef,
        metaCommentAckAwaitingSubstantiveBaselineSeqRef: ctx.metaCommentAckAwaitingSubstantiveBaselineSeqRef,
        substantiveInterviewQuestionDeliveredSeqRef: ctx.substantiveInterviewQuestionDeliveredSeqRef,
        recoveryAssistantSpokenAtSubstantiveSeqRef: ctx.recoveryAssistantSpokenAtSubstantiveSeqRef,
        metaCommentFrustrationCountByMomentRef: ctx.metaCommentFrustrationCountByMomentRef,
        inabilityCountByMomentRef: ctx.inabilityCountByMomentRef,
        skipRequestClassificationSeenByMomentRef: ctx.skipRequestClassificationSeenByMomentRef,
        scenarioCSophiePerspectiveProbeFiredRef: ctx.scenarioCSophiePerspectiveProbeFiredRef,
        probeLogRef: ctx.probeLogRef,
        elongatingProbeFiredRef: ctx.elongatingProbeFiredRef,
        personalHandoffInjectedRef: ctx.personalHandoffInjectedRef,
        interviewMomentsCompleteRef: ctx.interviewMomentsCompleteRef,
        scoredScenariosRef: ctx.scoredScenariosRef,
        scenarioScoresRef: ctx.scenarioScoresRef,
        scenarioAContemptProbeAskedRef: ctx.scenarioAContemptProbeAskedRef,
        scenarioARepairQuestionAskedRef: ctx.scenarioARepairQuestionAskedRef,
        s2RepairProbeDeliveredRef: ctx.s2RepairProbeDeliveredRef,
        s3RepairProbeDeliveredRef: ctx.s3RepairProbeDeliveredRef,
        scenarioAContemptProbeTtsDeliveredSessionRef: ctx.scenarioAContemptProbeTtsDeliveredSessionRef,
        moment4ThresholdProbeAskedRef: ctx.moment4ThresholdProbeAskedRef,
        deliveredReflectionRegistryRef: ctx.deliveredReflectionRegistryRef,
        moment4ClientSpecificityProbeInjectedRef: ctx.moment4ClientSpecificityProbeInjectedRef,
        moment4ExpectingPostSpecificityUserTurnRef: ctx.moment4ExpectingPostSpecificityUserTurnRef,
        moment4PostGrudgeSpecificityResolvedRef: ctx.moment4PostGrudgeSpecificityResolvedRef,
        moment4SpecificityScoringRef: ctx.moment4SpecificityScoringRef,
        deferredMoment4NarrativeRef: ctx.deferredMoment4NarrativeRef,
        moment5AccountabilityProbeFiredRef: ctx.moment5AccountabilityProbeFiredRef,
        moment5PostPromptUserTurnCountRef: ctx.moment5PostPromptUserTurnCountRef,
        moment5PrimaryAnchorDeliveredSessionRef: ctx.moment5PrimaryAnchorDeliveredSessionRef,
        moment5QuestionDeliveredRef: ctx.moment5QuestionDeliveredRef,
        moment5QuestionDeliveryInFlightRef: ctx.moment5QuestionDeliveryInFlightRef,
        moment5ResolutionFollowUpIssuedRef: ctx.moment5ResolutionFollowUpIssuedRef,
        moment5ResolutionDeliveredRef: ctx.moment5ResolutionDeliveredRef,
        moment5ClientScoringMetaRef: ctx.moment5ClientScoringMetaRef,
        moment5ConflictValidityClarificationIssuedRef: ctx.moment5ConflictValidityClarificationIssuedRef,
        moment5SpecificityRedirectIssuedRef: ctx.moment5SpecificityRedirectIssuedRef,
        waitingForClosingAdditionRef: ctx.waitingForClosingAdditionRef,
        lastAnsweredClosingScenarioRef: ctx.lastAnsweredClosingScenarioRef,
        lastClosingQuestionScenarioRef: ctx.lastClosingQuestionScenarioRef,
        closingQuestionAskedRef: ctx.closingQuestionAskedRef,
        closingQuestionAnsweredRef: ctx.closingQuestionAnsweredRef,
        skipContinuationSystemSuffixRef: ctx.skipContinuationSystemSuffixRef,
        resumeActiveScenarioRef: ctx.resumeActiveScenarioRef,
        isInterviewCompleteRef: ctx.isInterviewCompleteRef,
        pendingCompletionTranscriptRef: ctx.pendingCompletionTranscriptRef,
        pendingEmotionModalTransitionRef: ctx.pendingEmotionModalTransitionRef,
        resetScenarioCClientGatesOnly: ctx.resetScenarioCClientGatesOnly,
        emotionItemResponsesRef: ctx.emotionItemResponsesRef,
        recordInterviewAssistantDeliveryForMetaExemptionRef: ctx.recordInterviewAssistantDeliveryForMetaExemptionRef,
        finalizePendingMetaAckBaselineAfterAssistantTextRef: ctx.finalizePendingMetaAckBaselineAfterAssistantTextRef,
        pendingScenarioAContemptProbeStreamMuteRef: ctx.pendingScenarioAContemptProbeStreamMuteRef,
        pendingS3ToM4HandoffStreamMuteRef: ctx.pendingS3ToM4HandoffStreamMuteRef,
        resumeClosingRepeatSpeakInFlightRef: ctx.resumeClosingRepeatSpeakInFlightRef,
        resumeRepeatPrefetchMpegRef: ctx.resumeRepeatPrefetchMpegRef,
        routeChangedDuringRecordingRef: ctx.routeChangedDuringRecordingRef,
        scenarioCRepairOnlyEvidenceRef: ctx.scenarioCRepairOnlyEvidenceRef,
        scenarioFrustrationSkipNullMarkersRef: ctx.scenarioFrustrationSkipNullMarkersRef,
        scenarioSkipConfirmedCountRef: ctx.scenarioSkipConfirmedCountRef,
        scenarioSkipPenaltySumRef: ctx.scenarioSkipPenaltySumRef,
        lastUserTurnAudioDurationMsRef: ctx.lastUserTurnAudioDurationMsRef,
        lastUserTurnMicStopTelemetryRef: ctx.lastUserTurnMicStopTelemetryRef,
        lastVoiceTurnConfidenceRef: ctx.lastVoiceTurnConfidenceRef,
        lastVoiceTurnLanguageRef: ctx.lastVoiceTurnLanguageRef,
        responseTimingsRef: ctx.responseTimingsRef,
        timingRef: ctx.timingRef,
        resumeLoadingFlowActiveRef: ctx.resumeLoadingFlowActiveRef,
        resumeOfferWelcomeTtsRef: ctx.resumeOfferWelcomeTtsRef,
        interviewUserTurnEpochRef: ctx.interviewUserTurnEpochRef,
  } as PreClaudeTurnGateDeps;

}

export function syncAriaInterviewTurnHandlerCluster(
  refs: Pick<
    AriaInterviewDepsRefs,
    | 'kickPostClosingCompletionDepsRef'
    | 'scoreScenarioDepsRef'
    | 'postClaudeTurnDepsRef'
    | 'preClaudeTurnGateDepsRef'
  > & {
    processUserSpeechDepsRef: MutableRefObject<ProcessUserSpeechDeps>;
  },
  ctx: AriaInterviewDepsSyncContext,
  runtimeSyncCtx: AriaInterviewDepsSyncContext,
  processUserSpeechDepRefs: ProcessUserSpeechDepRefs,
  turnHandlerExtras: AriaInterviewDepsSyncContext = {},
  gateSyncCtx: AriaInterviewDepsSyncContext = {},
): void {
  const fullTurnHandlerCtx = mergeAriaInterviewSyncCtx(
    mergeAriaInterviewSyncCtx(
      mergeAriaInterviewSyncCtx(runtimeSyncCtx, ctx),
      turnHandlerExtras,
    ),
    gateSyncCtx,
  );
  syncAriaInterviewTurnHandlerDeps(refs, fullTurnHandlerCtx);
  syncProcessUserSpeechDeps(
    refs.processUserSpeechDepsRef,
    fullTurnHandlerCtx,
    processUserSpeechDepRefs,
  );
}

export function syncProcessUserSpeechDeps(
  ref: MutableRefObject<ProcessUserSpeechDeps>,
  ctx: AriaInterviewDepsSyncContext,
  depRefs: ProcessUserSpeechDepRefs,
): void {
  ref.current = {
    userId: ctx.userId,
    isAdmin: ctx.isAdmin,
    isInterviewAppRoute: ctx.isInterviewAppRoute,
    status: ctx.status,
    messages: ctx.messages,
    setVoiceState: ctx.setVoiceState,
    setIsWaiting: ctx.setIsWaiting,
    showChatError: ctx.showChatError,
    preClaudeTurnGateDepsRef: depRefs.preClaudeTurnGateDepsRef,
    claudeParallelStreamTtsDepsRef: depRefs.claudeParallelStreamTtsDepsRef,
    postClaudeTurnDepsRef: depRefs.postClaudeTurnDepsRef,
    whisperRatioReaskAttemptsForCurrentQuestionRef: ctx.whisperRatioReaskAttemptsForCurrentQuestionRef,
    resumeRepeatChoicePendingRef: ctx.resumeRepeatChoicePendingRef,
    resumeLastAssistantTextRef: ctx.resumeLastAssistantTextRef,
    lastQuestionTextRef: ctx.lastQuestionTextRef,
    parallelStreamingTtsRef: ctx.parallelStreamingTtsRef,
    interviewSessionIdRef: ctx.interviewSessionIdRef,
    metaClassificationForPendingAssistantRef: ctx.metaClassificationForPendingAssistantRef,
    moment5PostPromptUserTurnCountRef: ctx.moment5PostPromptUserTurnCountRef,
    moment5PrimaryAnchorDeliveredSessionRef: ctx.moment5PrimaryAnchorDeliveredSessionRef,
    moment5ResolutionFollowUpIssuedRef: ctx.moment5ResolutionFollowUpIssuedRef,
    moment5ResolutionDeliveredRef: ctx.moment5ResolutionDeliveredRef,
    currentInterviewMomentRef: ctx.currentInterviewMomentRef,
    scoredScenariosRef: ctx.scoredScenariosRef,
    scenarioScoresRef: ctx.scenarioScoresRef,
    resumeActiveScenarioRef: ctx.resumeActiveScenarioRef,
    resumeLoadingFlowActiveRef: ctx.resumeLoadingFlowActiveRef,
    resumeOfferWelcomeTtsRef: ctx.resumeOfferWelcomeTtsRef,
    interviewUserTurnEpochRef: ctx.interviewUserTurnEpochRef,
    interviewSessionAttemptIdRef: ctx.interviewSessionAttemptIdRef,
  } as ProcessUserSpeechDeps;
}
