import { spacing } from '@ui/theme/spacing';

export const ariaPreInterviewStyles = {
  introContent: { padding: spacing.lg, paddingTop: spacing.xxl },
  preInterviewScrollContent: {
    padding: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xxl * 2,
    maxWidth: 560,
    width: '100%',
    alignSelf: 'center',
  },
  preInterviewLogoWrap: { alignItems: 'center', marginBottom: spacing.md },
  preInterviewMainTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#F4F8FC',
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  preInterviewSubtitle: {
    fontSize: 15,
    color: '#7A9ABE',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.xl,
  },
  preInterviewSectionHeading: {
    fontSize: 17,
    fontWeight: '600',
    color: '#E8F0F8',
    marginBottom: spacing.md,
    textAlign: 'left',
    alignSelf: 'stretch',
  },
  preInterviewSectionHeadingSpaced: {
    marginTop: spacing.xl,
  },
  preInterviewBulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
    gap: 10,
    alignSelf: 'stretch',
  },
  preInterviewBulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#1E6FD9',
    marginTop: 8,
    flexShrink: 0,
  },
  preInterviewBulletText: {
    flex: 1,
    fontSize: 15,
    color: '#B8C9DC',
    lineHeight: 22,
  },
  preInterviewConsentCard: {
    marginTop: spacing.xl,
    padding: spacing.md,
    borderRadius: 12,
    backgroundColor: 'rgba(13, 17, 32, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(91, 168, 232, 0.22)',
    alignSelf: 'stretch',
    gap: spacing.md,
  },
  preInterviewCheckboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  preInterviewCheckboxBox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: 'rgba(91, 168, 232, 0.5)',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    flexShrink: 0,
  },
  preInterviewCheckboxBoxChecked: {
    backgroundColor: '#1E6FD9',
    borderColor: '#1E6FD9',
  },
  preInterviewCheckboxLabel: {
    flex: 1,
    fontSize: 15,
    color: '#E8F0F8',
    lineHeight: 22,
  },
  preInterviewBeginButton: {
    marginTop: spacing.lg,
    alignSelf: 'stretch',
    width: '100%',
  },
  preInterviewTipsBlock: {
    marginTop: spacing.lg,
    marginBottom: spacing.lg,
    gap: 12,
    alignSelf: 'stretch',
  },
  preInterviewTipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#1E6FD9',
    backgroundColor: 'rgba(30, 111, 217, 0.12)',
  },
  preInterviewTipIcon: {
    width: 32,
    textAlign: 'center',
    flexShrink: 0,
  },
  preInterviewTipLabel: {
    flex: 1,
    fontSize: 17,
    fontWeight: '600',
    color: '#F4F8FC',
    lineHeight: 24,
  },
  preInterviewLegalRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 32,
    marginTop: spacing.lg,
    flexWrap: 'wrap',
  },
  preInterviewLegalLink: {
    fontSize: 13,
    color: '#5BA8E8',
    textDecorationLine: 'underline',
  },
  headphoneRecommendCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: spacing.md,
    marginTop: spacing.lg,
    marginBottom: spacing.md,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#1E6FD9',
    backgroundColor: 'rgba(30, 111, 217, 0.12)',
  },
  /** Background-noise callout: same card treatment as headphones / desktop tips. */
  preInterviewNoiseTipCard: {
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  /** Tuck headphones card under the noise banner without double large gap. */
  preInterviewHeadphoneTipAfterNoise: {
    marginTop: spacing.sm,
  },
  /** Stack spacing after headphones tip when the desktop-browser tip is shown (web only). */
  preInterviewDesktopBrowserTipCard: {
    marginTop: spacing.sm,
    marginBottom: spacing.xl,
  },
  headphoneRecommendIcon: { marginRight: 12, marginTop: 2 },
  headphoneRecommendTextCol: { flex: 1 },
  headphoneRecommendTitle: {
    fontSize: 15,
    color: '#E8F0F8',
    lineHeight: 22,
    fontWeight: '500',
  },
  headphoneRecommendSub: {
    fontSize: 13,
    color: '#7A9ABE',
    lineHeight: 20,
    marginTop: 8,
  },
} as const;
