import { Platform } from 'react-native';
import { colors } from '@ui/theme/colors';
import { spacing } from '@ui/theme/spacing';

export const ariaActiveInterviewStyles = {
  activeContainer: { flex: 1 },
  activeHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border },
  activeHeaderLabel: { fontSize: 12, color: colors.primary },
  activeHeaderCount: { fontSize: 12, color: colors.textSecondary },
  constructRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, padding: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border },
  constructChip: { paddingVertical: 4, paddingHorizontal: 8, borderRadius: 4, borderWidth: 1, borderColor: colors.border },
  constructChipText: { fontSize: 10, color: colors.textSecondary },
  stageScoresContainer: { padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.surface },
  stageScoresTitle: { fontSize: 11, color: colors.primary, letterSpacing: 1, marginBottom: spacing.sm },
  stageScoreCard: { marginBottom: spacing.sm },
  stageScoreLabel: { fontSize: 12, fontWeight: '600', color: colors.text, marginBottom: 4 },
  stageScorePillars: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  stageScorePillar: { fontSize: 12, color: colors.textSecondary },
  transcriptScroll: { flex: 1 },
  transcriptContent: { padding: spacing.lg, paddingBottom: spacing.xl },
  msgRow: { marginBottom: spacing.lg },
  msgRowError: {
    alignSelf: 'center',
    maxWidth: '85%',
    padding: 12,
    marginVertical: 8,
    backgroundColor: 'rgba(232, 122, 122, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(232, 122, 122, 0.2)',
    borderRadius: 10,
  },
  msgContentError: {
    fontSize: 13,
    fontWeight: '300',
    color: '#E87A7A',
    textAlign: 'center',
    lineHeight: 20,
    borderLeftWidth: 0,
    paddingLeft: 0,
  },
  msgRowWaiting: {
    marginBottom: spacing.lg,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(82,142,220,0.08)',
  },
  msgRowUser: { alignItems: 'flex-end' },
  msgRole: { fontSize: 10, color: colors.primary, letterSpacing: 1, marginBottom: 4 },
  msgContent: { fontSize: 15, color: colors.text, lineHeight: 22, borderLeftWidth: 2, borderLeftColor: colors.border, paddingLeft: spacing.sm },
  msgContentWaiting: { color: '#3D5470', fontStyle: 'italic' },
  scoreCard: {
    marginVertical: spacing.md,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderLeftWidth: 3,
    borderColor: colors.border,
    borderLeftColor: colors.primary,
    borderRadius: 8,
  },
  scoreCardContent: { fontSize: 12, color: colors.textSecondary, lineHeight: 20, fontFamily: Platform.OS === 'web' ? 'monospace' : undefined },
  voiceDock: { padding: spacing.lg, alignItems: 'center', borderTopWidth: 1, borderTopColor: colors.border },
  dockError: { fontSize: 13, color: colors.error, marginBottom: spacing.sm },
  dockWarning: { fontSize: 13, color: colors.warning, marginBottom: spacing.sm },
  micOrb: { width: 88, height: 88, borderRadius: 44, backgroundColor: colors.text, justifyContent: 'center', alignItems: 'center' },
  micOrbListening: { backgroundColor: colors.error },
  micOrbProcessing: { backgroundColor: colors.primary },
  micOrbSpeaking: { backgroundColor: colors.success },
  voiceLabel: { fontSize: 11, color: colors.textSecondary, marginTop: spacing.sm },
  typeFallback: { marginTop: spacing.lg, width: '100%', maxWidth: 360 },
  typeFallbackLabel: { fontSize: 12, color: colors.textSecondary, marginBottom: spacing.xs },
  typeFallbackInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: 15,
    color: colors.text,
    backgroundColor: colors.surface,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  typeFallbackButton: { marginTop: spacing.sm },
  chatCompletionBlock: { marginTop: spacing.lg, padding: spacing.lg, backgroundColor: colors.surface, borderRadius: 8, borderLeftWidth: 4, borderLeftColor: colors.primary },
  chatCompletionTitle: { fontSize: 14, fontWeight: '600', color: colors.primary, letterSpacing: 1, marginBottom: spacing.sm },
  chatCompletionSummary: { fontSize: 15, color: colors.textSecondary, lineHeight: 22, marginBottom: spacing.lg },
  chatCompletionButton: { alignSelf: 'flex-start' },
} as const;
