import { Platform } from 'react-native';

export const ariaAdminInterviewStyles = {
  // Admin interview — dark design system (void/surface/flame-bright/text-primary)
  adminActiveContainer: { flex: 1, backgroundColor: '#05060D' },
  introBackButton: {
    position: 'absolute',
    top: 16,
    left: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(30,111,217,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.2)',
    borderRadius: 6,
    zIndex: 100,
  },
  introLogoutButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(30,111,217,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.2)',
    borderRadius: 6,
    zIndex: 100,
  },
  introLogoutButtonText: {
    fontFamily: Platform.OS === 'web' ? 'Jost, sans-serif' : undefined,
    fontSize: 11,
    fontWeight: '400',
    letterSpacing: 1.5,
    color: '#5BA8E8',
  },
  adminPanelButton: {
    position: 'absolute',
    top: 16,
    left: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(30,111,217,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.2)',
    borderRadius: 6,
    zIndex: 100,
  },
  adminTopBarRow: {
    position: 'absolute',
    top: 16,
    left: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    zIndex: 100,
  },
  adminBarButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(30,111,217,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.2)',
    borderRadius: 6,
  },
  adminBarButtonReset: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(184,92,92,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(232,120,120,0.35)',
    borderRadius: 6,
  },
  adminBarButtonLogout: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(30,111,217,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.2)',
    borderRadius: 6,
  },
  adminPanelButtonText: {
    fontFamily: Platform.OS === 'web' ? 'Jost, sans-serif' : undefined,
    fontSize: 10,
    fontWeight: '300',
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: '#5BA8E8',
  },
  adminResetButtonText: {
    fontFamily: Platform.OS === 'web' ? 'Jost, sans-serif' : undefined,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: '#E8A0A0',
  },
  adminLogoutButtonText: {
    fontFamily: Platform.OS === 'web' ? 'Jost, sans-serif' : undefined,
    fontSize: 10,
    fontWeight: '400',
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: '#5BA8E8',
  },
  adminWrap: { flex: 1, backgroundColor: '#05060D' },
  adminStageScoresContainer: { backgroundColor: '#0D1120', borderBottomColor: 'rgba(82,142,220,0.12)' },
  adminStageScoresTitle: { color: '#3D5470', letterSpacing: 2.5, textTransform: 'uppercase', fontFamily: Platform.OS === 'web' ? 'Jost, sans-serif' : undefined, fontSize: 10 },
  adminTranscriptScroll: { backgroundColor: '#05060D' },
  adminTranscriptContent: { backgroundColor: '#05060D' },
  adminMsgRole: { color: '#3D5470', fontSize: 10, letterSpacing: 1 },
  adminMsgContentInterviewer: { color: '#C8E4FF', fontFamily: Platform.OS === 'web' ? "'Cormorant Garamond', serif" : undefined, fontSize: 16, fontWeight: '300', fontStyle: 'italic', lineHeight: 24, borderLeftColor: 'rgba(82,142,220,0.12)' },
  adminMsgContentUser: { color: '#E8F0F8', fontFamily: Platform.OS === 'web' ? 'Jost, sans-serif' : undefined, fontSize: 14, fontWeight: '300', lineHeight: 21 },
  adminScoreCard: { backgroundColor: '#111827', borderColor: 'rgba(82,142,220,0.12)', borderLeftColor: '#5BA8E8' },
  adminScoreCardContent: { color: '#C8E4FF', fontSize: 12 },
  adminStageScoreCard: { backgroundColor: '#111827', borderColor: 'rgba(82,142,220,0.12)', borderRadius: 10, padding: 16 },
  adminStageScoreLabel: { fontFamily: Platform.OS === 'web' ? 'Jost, sans-serif' : undefined, fontSize: 9, fontWeight: '400', letterSpacing: 2.5, textTransform: 'uppercase', color: '#3D5470' },
  adminStageScorePillar: { fontFamily: Platform.OS === 'web' ? "'Cormorant Garamond', serif" : undefined, fontSize: 22, fontWeight: '300', color: '#C8E4FF' },
  adminMsgRowWaiting: { borderBottomColor: 'rgba(82,142,220,0.12)' },
  adminMsgContentWaiting: { color: '#3D5470' },
  adminVoiceDock: { borderTopColor: 'rgba(82,142,220,0.12)', backgroundColor: '#05060D' },
  adminDockText: { color: '#E8F0F8' },
  adminVoiceLabel: { color: '#7A9ABE' },
  adminTypeFallbackLabel: { color: '#7A9ABE' },
  adminTypeFallbackInput: { backgroundColor: '#0D1120', borderColor: 'rgba(82,142,220,0.12)', color: '#E8F0F8' },
} as const;
