import { Platform } from 'react-native';
import { colors } from '@ui/theme/colors';

export const ariaScreenShellStyles = {
  container: { flex: 1 },
  sessionExpiredOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 9999,
    backgroundColor: 'rgba(5,6,13,0.96)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  sessionExpiredTitle: {
    fontFamily: Platform.OS === 'web' ? "'Cormorant Garamond', serif" : undefined,
    fontSize: 24,
    fontWeight: '300',
    color: '#C8E4FF',
    marginBottom: 14,
    textAlign: 'center',
  },
  sessionExpiredBody: {
    fontFamily: Platform.OS === 'web' ? "'Jost', sans-serif" : undefined,
    fontSize: 14,
    fontWeight: '300',
    color: '#7A9ABE',
    lineHeight: 24,
    maxWidth: 320,
    marginBottom: 32,
    textAlign: 'center',
  },
  sessionExpiredButton: {
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 10,
    backgroundColor: colors.primary,
    shadowColor: '#1E6FD9',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 30,
    elevation: 8,
  },
  sessionExpiredButtonLabel: {
    fontFamily: Platform.OS === 'web' ? "'Jost', sans-serif" : undefined,
    fontSize: 11,
    fontWeight: '400',
    letterSpacing: 2.5,
    textTransform: 'uppercase',
    color: '#EEF6FF',
  },
  memoryFallbackBanner: {
    position: 'absolute',
    bottom: 100,
    left: '50%',
    marginLeft: -140,
    width: 280,
    backgroundColor: 'rgba(13,17,32,0.95)',
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.2)',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 18,
    zIndex: 500,
    alignItems: 'center',
    justifyContent: 'center',
  },
  memoryFallbackBannerText: {
    fontFamily: Platform.OS === 'web' ? "'Jost', sans-serif" : undefined,
    fontSize: 11,
    fontWeight: '300',
    color: '#7A9ABE',
    letterSpacing: 0.5,
  },
} as const;
