import { Platform } from 'react-native';
import { colors } from '@ui/theme/colors';
import { spacing } from '@ui/theme/spacing';

export const ariaScoringResultsPanelStyles = {
  scoringIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  scoringIndicatorDot: { fontSize: 11, color: colors.primary, letterSpacing: 2 },
  scoringIndicatorText: { fontSize: 11, color: colors.textSecondary, letterSpacing: 1 },
  scoringIndicatorSub: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 4,
    opacity: 0.9,
  },
  scoringViewScoresButton: {
    marginTop: 12,
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignSelf: 'flex-start',
  },
  scoringViewScoresButtonLabel: {
    fontSize: 11,
    fontWeight: '400',
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: '#EEF6FF',
  },
  resultsPanel: {
    borderTopWidth: 2,
    borderTopColor: colors.primary,
    backgroundColor: colors.surface,
    maxHeight: 360,
  },
  resultsPanelHighlight: {
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  resultsPanelContent: { padding: 24, paddingBottom: spacing.xl },
  resultsPanelTitle: {
    fontSize: 10,
    color: colors.primary,
    letterSpacing: 3,
    marginBottom: 12,
  },
  gateResultBlock: {
    borderWidth: 1,
    borderLeftWidth: 4,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  gateResultLabel: {
    fontSize: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  gateResultText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 22,
  },
  resultsPanelSummary: {
    fontSize: 14,
    lineHeight: 22,
    color: colors.textSecondary,
    marginBottom: 20,
  },
  resultsReferFriendBlock: {
    marginBottom: 20,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 16,
  },
  resultsReferFriendTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 10,
  },
  resultsReferFriendBody: {
    fontSize: 14,
    lineHeight: 22,
    color: colors.textSecondary,
    marginBottom: 14,
  },
  resultsReferCodeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  resultsReferCodeText: {
    flex: 1,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 1,
    color: colors.text,
  },
  resultsReferCopyBtn: {
    backgroundColor: 'rgba(59,130,246,0.18)',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  resultsReferCopyBtnLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primary,
  },
  resultsPanelPillars: { marginBottom: 20 },
  resultsPillarRow: { marginBottom: 10 },
  resultsPillarHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  resultsPillarName: { fontSize: 10, color: colors.textSecondary, letterSpacing: 1 },
  resultsPillarScore: { fontSize: 11, fontWeight: '600' },
  resultsPillarBar: { height: 3, backgroundColor: colors.border, borderRadius: 2 },
  resultsPillarBarFill: { height: '100%', borderRadius: 2 },
  resultsPanelButton: { width: '100%' },
  retakeButtonUnderReview: {
    marginTop: 32,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderWidth: 1,
    borderColor: 'rgba(82,142,220,0.4)',
    borderRadius: 8,
  },
  retakeButtonUnderReviewText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#7A9ABE',
    letterSpacing: 1,
  },
} as const;
